/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/hazelcast/hazelcast-platform-operator/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCronHotBackups implements CronHotBackupInterface
type FakeCronHotBackups struct {
	Fake *FakeHazelcastV1alpha1
	ns   string
}

var cronhotbackupsResource = schema.GroupVersionResource{Group: "hazelcast", Version: "v1alpha1", Resource: "cronhotbackups"}

var cronhotbackupsKind = schema.GroupVersionKind{Group: "hazelcast", Version: "v1alpha1", Kind: "CronHotBackup"}

// Get takes name of the cronHotBackup, and returns the corresponding cronHotBackup object, and an error if there is any.
func (c *FakeCronHotBackups) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.CronHotBackup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(cronhotbackupsResource, c.ns, name), &v1alpha1.CronHotBackup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CronHotBackup), err
}

// List takes label and field selectors, and returns the list of CronHotBackups that match those selectors.
func (c *FakeCronHotBackups) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CronHotBackupList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(cronhotbackupsResource, cronhotbackupsKind, c.ns, opts), &v1alpha1.CronHotBackupList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CronHotBackupList{ListMeta: obj.(*v1alpha1.CronHotBackupList).ListMeta}
	for _, item := range obj.(*v1alpha1.CronHotBackupList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested cronHotBackups.
func (c *FakeCronHotBackups) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(cronhotbackupsResource, c.ns, opts))

}

// Create takes the representation of a cronHotBackup and creates it.  Returns the server's representation of the cronHotBackup, and an error, if there is any.
func (c *FakeCronHotBackups) Create(ctx context.Context, cronHotBackup *v1alpha1.CronHotBackup, opts v1.CreateOptions) (result *v1alpha1.CronHotBackup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(cronhotbackupsResource, c.ns, cronHotBackup), &v1alpha1.CronHotBackup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CronHotBackup), err
}

// Update takes the representation of a cronHotBackup and updates it. Returns the server's representation of the cronHotBackup, and an error, if there is any.
func (c *FakeCronHotBackups) Update(ctx context.Context, cronHotBackup *v1alpha1.CronHotBackup, opts v1.UpdateOptions) (result *v1alpha1.CronHotBackup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(cronhotbackupsResource, c.ns, cronHotBackup), &v1alpha1.CronHotBackup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CronHotBackup), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCronHotBackups) UpdateStatus(ctx context.Context, cronHotBackup *v1alpha1.CronHotBackup, opts v1.UpdateOptions) (*v1alpha1.CronHotBackup, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(cronhotbackupsResource, "status", c.ns, cronHotBackup), &v1alpha1.CronHotBackup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CronHotBackup), err
}

// Delete takes name of the cronHotBackup and deletes it. Returns an error if one occurs.
func (c *FakeCronHotBackups) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(cronhotbackupsResource, c.ns, name, opts), &v1alpha1.CronHotBackup{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCronHotBackups) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(cronhotbackupsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.CronHotBackupList{})
	return err
}

// Patch applies the patch and returns the patched cronHotBackup.
func (c *FakeCronHotBackups) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CronHotBackup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(cronhotbackupsResource, c.ns, name, pt, data, subresources...), &v1alpha1.CronHotBackup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CronHotBackup), err
}
