/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/hazelcast/hazelcast-platform-operator/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMultiMaps implements MultiMapInterface
type FakeMultiMaps struct {
	Fake *FakeHazelcastV1alpha1
	ns   string
}

var multimapsResource = schema.GroupVersionResource{Group: "hazelcast", Version: "v1alpha1", Resource: "multimaps"}

var multimapsKind = schema.GroupVersionKind{Group: "hazelcast", Version: "v1alpha1", Kind: "MultiMap"}

// Get takes name of the multiMap, and returns the corresponding multiMap object, and an error if there is any.
func (c *FakeMultiMaps) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MultiMap, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(multimapsResource, c.ns, name), &v1alpha1.MultiMap{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MultiMap), err
}

// List takes label and field selectors, and returns the list of MultiMaps that match those selectors.
func (c *FakeMultiMaps) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MultiMapList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(multimapsResource, multimapsKind, c.ns, opts), &v1alpha1.MultiMapList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.MultiMapList{ListMeta: obj.(*v1alpha1.MultiMapList).ListMeta}
	for _, item := range obj.(*v1alpha1.MultiMapList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested multiMaps.
func (c *FakeMultiMaps) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(multimapsResource, c.ns, opts))

}

// Create takes the representation of a multiMap and creates it.  Returns the server's representation of the multiMap, and an error, if there is any.
func (c *FakeMultiMaps) Create(ctx context.Context, multiMap *v1alpha1.MultiMap, opts v1.CreateOptions) (result *v1alpha1.MultiMap, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(multimapsResource, c.ns, multiMap), &v1alpha1.MultiMap{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MultiMap), err
}

// Update takes the representation of a multiMap and updates it. Returns the server's representation of the multiMap, and an error, if there is any.
func (c *FakeMultiMaps) Update(ctx context.Context, multiMap *v1alpha1.MultiMap, opts v1.UpdateOptions) (result *v1alpha1.MultiMap, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(multimapsResource, c.ns, multiMap), &v1alpha1.MultiMap{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MultiMap), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMultiMaps) UpdateStatus(ctx context.Context, multiMap *v1alpha1.MultiMap, opts v1.UpdateOptions) (*v1alpha1.MultiMap, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(multimapsResource, "status", c.ns, multiMap), &v1alpha1.MultiMap{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MultiMap), err
}

// Delete takes name of the multiMap and deletes it. Returns an error if one occurs.
func (c *FakeMultiMaps) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(multimapsResource, c.ns, name, opts), &v1alpha1.MultiMap{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMultiMaps) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(multimapsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.MultiMapList{})
	return err
}

// Patch applies the patch and returns the patched multiMap.
func (c *FakeMultiMaps) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MultiMap, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(multimapsResource, c.ns, name, pt, data, subresources...), &v1alpha1.MultiMap{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MultiMap), err
}
