/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/hazelcast/hazelcast-platform-operator/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMaps implements MapInterface
type FakeMaps struct {
	Fake *FakeHazelcastV1alpha1
	ns   string
}

var mapsResource = schema.GroupVersionResource{Group: "hazelcast", Version: "v1alpha1", Resource: "maps"}

var mapsKind = schema.GroupVersionKind{Group: "hazelcast", Version: "v1alpha1", Kind: "Map"}

// Get takes name of the map, and returns the corresponding map object, and an error if there is any.
func (c *FakeMaps) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Map, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(mapsResource, c.ns, name), &v1alpha1.Map{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Map), err
}

// List takes label and field selectors, and returns the list of Maps that match those selectors.
func (c *FakeMaps) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MapList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(mapsResource, mapsKind, c.ns, opts), &v1alpha1.MapList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.MapList{ListMeta: obj.(*v1alpha1.MapList).ListMeta}
	for _, item := range obj.(*v1alpha1.MapList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested maps.
func (c *FakeMaps) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(mapsResource, c.ns, opts))

}

// Create takes the representation of a map and creates it.  Returns the server's representation of the map, and an error, if there is any.
func (c *FakeMaps) Create(ctx context.Context, m *v1alpha1.Map, opts v1.CreateOptions) (result *v1alpha1.Map, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(mapsResource, c.ns, m), &v1alpha1.Map{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Map), err
}

// Update takes the representation of a map and updates it. Returns the server's representation of the map, and an error, if there is any.
func (c *FakeMaps) Update(ctx context.Context, m *v1alpha1.Map, opts v1.UpdateOptions) (result *v1alpha1.Map, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(mapsResource, c.ns, m), &v1alpha1.Map{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Map), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMaps) UpdateStatus(ctx context.Context, m *v1alpha1.Map, opts v1.UpdateOptions) (*v1alpha1.Map, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(mapsResource, "status", c.ns, m), &v1alpha1.Map{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Map), err
}

// Delete takes name of the map and deletes it. Returns an error if one occurs.
func (c *FakeMaps) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(mapsResource, c.ns, name, opts), &v1alpha1.Map{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMaps) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(mapsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.MapList{})
	return err
}

// Patch applies the patch and returns the patched map.
func (c *FakeMaps) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Map, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(mapsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Map{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Map), err
}
