/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/hazelcast/hazelcast-platform-operator/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeManagementCenters implements ManagementCenterInterface
type FakeManagementCenters struct {
	Fake *FakeHazelcastV1alpha1
	ns   string
}

var managementcentersResource = schema.GroupVersionResource{Group: "hazelcast", Version: "v1alpha1", Resource: "managementcenters"}

var managementcentersKind = schema.GroupVersionKind{Group: "hazelcast", Version: "v1alpha1", Kind: "ManagementCenter"}

// Get takes name of the managementCenter, and returns the corresponding managementCenter object, and an error if there is any.
func (c *FakeManagementCenters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ManagementCenter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(managementcentersResource, c.ns, name), &v1alpha1.ManagementCenter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManagementCenter), err
}

// List takes label and field selectors, and returns the list of ManagementCenters that match those selectors.
func (c *FakeManagementCenters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ManagementCenterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(managementcentersResource, managementcentersKind, c.ns, opts), &v1alpha1.ManagementCenterList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ManagementCenterList{ListMeta: obj.(*v1alpha1.ManagementCenterList).ListMeta}
	for _, item := range obj.(*v1alpha1.ManagementCenterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested managementCenters.
func (c *FakeManagementCenters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(managementcentersResource, c.ns, opts))

}

// Create takes the representation of a managementCenter and creates it.  Returns the server's representation of the managementCenter, and an error, if there is any.
func (c *FakeManagementCenters) Create(ctx context.Context, managementCenter *v1alpha1.ManagementCenter, opts v1.CreateOptions) (result *v1alpha1.ManagementCenter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(managementcentersResource, c.ns, managementCenter), &v1alpha1.ManagementCenter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManagementCenter), err
}

// Update takes the representation of a managementCenter and updates it. Returns the server's representation of the managementCenter, and an error, if there is any.
func (c *FakeManagementCenters) Update(ctx context.Context, managementCenter *v1alpha1.ManagementCenter, opts v1.UpdateOptions) (result *v1alpha1.ManagementCenter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(managementcentersResource, c.ns, managementCenter), &v1alpha1.ManagementCenter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManagementCenter), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeManagementCenters) UpdateStatus(ctx context.Context, managementCenter *v1alpha1.ManagementCenter, opts v1.UpdateOptions) (*v1alpha1.ManagementCenter, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(managementcentersResource, "status", c.ns, managementCenter), &v1alpha1.ManagementCenter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManagementCenter), err
}

// Delete takes name of the managementCenter and deletes it. Returns an error if one occurs.
func (c *FakeManagementCenters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(managementcentersResource, c.ns, name, opts), &v1alpha1.ManagementCenter{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeManagementCenters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(managementcentersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ManagementCenterList{})
	return err
}

// Patch applies the patch and returns the patched managementCenter.
func (c *FakeManagementCenters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ManagementCenter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(managementcentersResource, c.ns, name, pt, data, subresources...), &v1alpha1.ManagementCenter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManagementCenter), err
}
