/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/hazelcast/hazelcast-platform-operator/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeReplicatedMaps implements ReplicatedMapInterface
type FakeReplicatedMaps struct {
	Fake *FakeHazelcastV1alpha1
	ns   string
}

var replicatedmapsResource = schema.GroupVersionResource{Group: "hazelcast", Version: "v1alpha1", Resource: "replicatedmaps"}

var replicatedmapsKind = schema.GroupVersionKind{Group: "hazelcast", Version: "v1alpha1", Kind: "ReplicatedMap"}

// Get takes name of the replicatedMap, and returns the corresponding replicatedMap object, and an error if there is any.
func (c *FakeReplicatedMaps) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ReplicatedMap, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(replicatedmapsResource, c.ns, name), &v1alpha1.ReplicatedMap{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ReplicatedMap), err
}

// List takes label and field selectors, and returns the list of ReplicatedMaps that match those selectors.
func (c *FakeReplicatedMaps) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ReplicatedMapList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(replicatedmapsResource, replicatedmapsKind, c.ns, opts), &v1alpha1.ReplicatedMapList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ReplicatedMapList{ListMeta: obj.(*v1alpha1.ReplicatedMapList).ListMeta}
	for _, item := range obj.(*v1alpha1.ReplicatedMapList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested replicatedMaps.
func (c *FakeReplicatedMaps) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(replicatedmapsResource, c.ns, opts))

}

// Create takes the representation of a replicatedMap and creates it.  Returns the server's representation of the replicatedMap, and an error, if there is any.
func (c *FakeReplicatedMaps) Create(ctx context.Context, replicatedMap *v1alpha1.ReplicatedMap, opts v1.CreateOptions) (result *v1alpha1.ReplicatedMap, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(replicatedmapsResource, c.ns, replicatedMap), &v1alpha1.ReplicatedMap{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ReplicatedMap), err
}

// Update takes the representation of a replicatedMap and updates it. Returns the server's representation of the replicatedMap, and an error, if there is any.
func (c *FakeReplicatedMaps) Update(ctx context.Context, replicatedMap *v1alpha1.ReplicatedMap, opts v1.UpdateOptions) (result *v1alpha1.ReplicatedMap, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(replicatedmapsResource, c.ns, replicatedMap), &v1alpha1.ReplicatedMap{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ReplicatedMap), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeReplicatedMaps) UpdateStatus(ctx context.Context, replicatedMap *v1alpha1.ReplicatedMap, opts v1.UpdateOptions) (*v1alpha1.ReplicatedMap, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(replicatedmapsResource, "status", c.ns, replicatedMap), &v1alpha1.ReplicatedMap{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ReplicatedMap), err
}

// Delete takes name of the replicatedMap and deletes it. Returns an error if one occurs.
func (c *FakeReplicatedMaps) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(replicatedmapsResource, c.ns, name, opts), &v1alpha1.ReplicatedMap{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeReplicatedMaps) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(replicatedmapsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ReplicatedMapList{})
	return err
}

// Patch applies the patch and returns the patched replicatedMap.
func (c *FakeReplicatedMaps) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ReplicatedMap, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(replicatedmapsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ReplicatedMap{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ReplicatedMap), err
}
