coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
codecov:
  bot: hazelcast
  notify:
    wait_for_ci: true
  require_ci_to_pass: false