commitish: 'main'
autolabeler:
  - label: 'feature'
    branch:
      - '/feat\/.+/'
    title:
      - '/feature/i'
      - '/feat/i'
  - label: 'enhancement'
    branch:
      - '/enhancement\/.+/'
    title:
      - '/enhancement/i'
      - '/improve/i'
      - '/upgrade/i'
      - '/update/i'
  - label: 'fix'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
      - '/bug/i'
      - '/issue/i'
      - '/error/i'
  - label: 'ci'
    files:
      - '.github/workflows/*'
  - label: 'documentation'
    files:
      - '*.md'