commitish: 'main'
categories:
  - title: 'New Features'
    labels:
      - 'feature'
  - title: 'Changes'
    labels:
      - 'enhancement'
  - title: 'Fixed Issues'
    labels:
      - 'fix'
include-labels:
  - 'feature'
  - 'enhancement'
  - 'fix'
exclude-labels:
  - 'non-release'
  - 'ci'
  - 'documentation'
replacers:
  - search: '/(<!.*)\s+/gm'
    replace: ''
  - search: '/^(## User Impact)/gm'
    replace: '### User Impact'
  - search: '/(((?<=(#\d\d\d)\)(.*?))[^#]*((?=### User Impact)))|(### User Impact)|((?<=(#\d\d\d)\)(.*?)))##*)|(### User Impact)|((?<=(#\d\d\d)\)(.*?)))##*|(?<=(#\d\d\d)\)(.*?))[^#]*((?:#L).*)|((?<=(#\d\d\d)\)(.*?))[^#]*((?=\n)))/gm'
    replace: ''
  - search: '/(?=^[a-zA-Z`])^(?!In this release)/gm'
    replace: '    - '
  - search: '/\[(.*?)\]/g'
    replace: ''
  - search: '^Add'
    replace: 'Added'
  - search: 'feat:'
    replace: ''
  - search: 'fix:'
    replace: ''
  - search: 'enhancement:'
    replace: ''
autolabeler:
  - label: 'feature'
    branch:
      - '/feat\/.+/'
    title:
      - '/feature/i'
      - '/feat/i'
  - label: 'enhancement'
    branch:
      - '/enhancement\/.+/'
    title:
      - '/enhancement/i'
      - '/improve/i'
      - '/upgrade/i'
      - '/update/i'
  - label: 'fix'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
      - '/bug/i'
      - '/issue/i'
      - '/error/i'
  - label: 'ci'
    files:
      - '.github/workflows/*'
  - label: 'documentation'
    files:
      - '*.md'
change-template: '- $TITLE (#$NUMBER)$BODY'
template: |
  # Release notes
  In this release, we introduced the {REPLACE THIS}. We also introduced {REPLACE THIS}.
  $CHANGES
