/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"net/http"

	v1alpha1 "github.com/hazelcast/hazelcast-platform-operator/api/v1alpha1"
	"github.com/hazelcast/hazelcast-platform-operator/pkg/k8s/hazelcast/scheme"
	rest "k8s.io/client-go/rest"
)

type HazelcastV1alpha1Interface interface {
	RESTClient() rest.Interface
	CachesGetter
	CronHotBackupsGetter
	HazelcastsGetter
	HotBackupsGetter
	ManagementCentersGetter
	MapsGetter
	MultiMapsGetter
	QueuesGetter
	ReplicatedMapsGetter
	TopicsGetter
	WanReplicationsGetter
}

// HazelcastV1alpha1Client is used to interact with features provided by the hazelcast group.
type HazelcastV1alpha1Client struct {
	restClient rest.Interface
}

func (c *HazelcastV1alpha1Client) Caches(namespace string) CacheInterface {
	return newCaches(c, namespace)
}

func (c *HazelcastV1alpha1Client) CronHotBackups(namespace string) CronHotBackupInterface {
	return newCronHotBackups(c, namespace)
}

func (c *HazelcastV1alpha1Client) Hazelcasts(namespace string) HazelcastInterface {
	return newHazelcasts(c, namespace)
}

func (c *HazelcastV1alpha1Client) HotBackups(namespace string) HotBackupInterface {
	return newHotBackups(c, namespace)
}

func (c *HazelcastV1alpha1Client) ManagementCenters(namespace string) ManagementCenterInterface {
	return newManagementCenters(c, namespace)
}

func (c *HazelcastV1alpha1Client) Maps(namespace string) MapInterface {
	return newMaps(c, namespace)
}

func (c *HazelcastV1alpha1Client) MultiMaps(namespace string) MultiMapInterface {
	return newMultiMaps(c, namespace)
}

func (c *HazelcastV1alpha1Client) Queues(namespace string) QueueInterface {
	return newQueues(c, namespace)
}

func (c *HazelcastV1alpha1Client) ReplicatedMaps(namespace string) ReplicatedMapInterface {
	return newReplicatedMaps(c, namespace)
}

func (c *HazelcastV1alpha1Client) Topics(namespace string) TopicInterface {
	return newTopics(c, namespace)
}

func (c *HazelcastV1alpha1Client) WanReplications(namespace string) WanReplicationInterface {
	return newWanReplications(c, namespace)
}

// NewForConfig creates a new HazelcastV1alpha1Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*HazelcastV1alpha1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new HazelcastV1alpha1Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*HazelcastV1alpha1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &HazelcastV1alpha1Client{client}, nil
}

// NewForConfigOrDie creates a new HazelcastV1alpha1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *HazelcastV1alpha1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new HazelcastV1alpha1Client for the given RESTClient.
func New(c rest.Interface) *HazelcastV1alpha1Client {
	return &HazelcastV1alpha1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1alpha1.GroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *HazelcastV1alpha1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
