/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/hazelcast/hazelcast-platform-operator/api/v1alpha1"
	scheme "github.com/hazelcast/hazelcast-platform-operator/pkg/k8s/hazelcast/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// HotBackupsGetter has a method to return a HotBackupInterface.
// A group's client should implement this interface.
type HotBackupsGetter interface {
	HotBackups(namespace string) HotBackupInterface
}

// HotBackupInterface has methods to work with HotBackup resources.
type HotBackupInterface interface {
	Create(ctx context.Context, hotBackup *v1alpha1.HotBackup, opts v1.CreateOptions) (*v1alpha1.HotBackup, error)
	Update(ctx context.Context, hotBackup *v1alpha1.HotBackup, opts v1.UpdateOptions) (*v1alpha1.HotBackup, error)
	UpdateStatus(ctx context.Context, hotBackup *v1alpha1.HotBackup, opts v1.UpdateOptions) (*v1alpha1.HotBackup, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.HotBackup, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.HotBackupList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.HotBackup, err error)
	HotBackupExpansion
}

// hotBackups implements HotBackupInterface
type hotBackups struct {
	client rest.Interface
	ns     string
}

// newHotBackups returns a HotBackups
func newHotBackups(c *HazelcastV1alpha1Client, namespace string) *hotBackups {
	return &hotBackups{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the hotBackup, and returns the corresponding hotBackup object, and an error if there is any.
func (c *hotBackups) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.HotBackup, err error) {
	result = &v1alpha1.HotBackup{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("hotbackups").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of HotBackups that match those selectors.
func (c *hotBackups) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.HotBackupList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.HotBackupList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("hotbackups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested hotBackups.
func (c *hotBackups) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("hotbackups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a hotBackup and creates it.  Returns the server's representation of the hotBackup, and an error, if there is any.
func (c *hotBackups) Create(ctx context.Context, hotBackup *v1alpha1.HotBackup, opts v1.CreateOptions) (result *v1alpha1.HotBackup, err error) {
	result = &v1alpha1.HotBackup{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("hotbackups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(hotBackup).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a hotBackup and updates it. Returns the server's representation of the hotBackup, and an error, if there is any.
func (c *hotBackups) Update(ctx context.Context, hotBackup *v1alpha1.HotBackup, opts v1.UpdateOptions) (result *v1alpha1.HotBackup, err error) {
	result = &v1alpha1.HotBackup{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("hotbackups").
		Name(hotBackup.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(hotBackup).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *hotBackups) UpdateStatus(ctx context.Context, hotBackup *v1alpha1.HotBackup, opts v1.UpdateOptions) (result *v1alpha1.HotBackup, err error) {
	result = &v1alpha1.HotBackup{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("hotbackups").
		Name(hotBackup.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(hotBackup).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the hotBackup and deletes it. Returns an error if one occurs.
func (c *hotBackups) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("hotbackups").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *hotBackups) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("hotbackups").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched hotBackup.
func (c *hotBackups) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.HotBackup, err error) {
	result = &v1alpha1.HotBackup{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("hotbackups").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
