/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/hazelcast/hazelcast-platform-operator/api/v1alpha1"
	scheme "github.com/hazelcast/hazelcast-platform-operator/pkg/k8s/hazelcast/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MapsGetter has a method to return a MapInterface.
// A group's client should implement this interface.
type MapsGetter interface {
	Maps(namespace string) MapInterface
}

// MapInterface has methods to work with Map resources.
type MapInterface interface {
	Create(ctx context.Context, m *v1alpha1.Map, opts v1.CreateOptions) (*v1alpha1.Map, error)
	Update(ctx context.Context, m *v1alpha1.Map, opts v1.UpdateOptions) (*v1alpha1.Map, error)
	UpdateStatus(ctx context.Context, m *v1alpha1.Map, opts v1.UpdateOptions) (*v1alpha1.Map, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Map, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.MapList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Map, err error)
	MapExpansion
}

// maps implements MapInterface
type maps struct {
	client rest.Interface
	ns     string
}

// newMaps returns a Maps
func newMaps(c *HazelcastV1alpha1Client, namespace string) *maps {
	return &maps{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the map, and returns the corresponding map object, and an error if there is any.
func (c *maps) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Map, err error) {
	result = &v1alpha1.Map{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("maps").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Maps that match those selectors.
func (c *maps) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MapList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.MapList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("maps").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested maps.
func (c *maps) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("maps").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a map and creates it.  Returns the server's representation of the map, and an error, if there is any.
func (c *maps) Create(ctx context.Context, m *v1alpha1.Map, opts v1.CreateOptions) (result *v1alpha1.Map, err error) {
	result = &v1alpha1.Map{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("maps").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(m).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a map and updates it. Returns the server's representation of the map, and an error, if there is any.
func (c *maps) Update(ctx context.Context, m *v1alpha1.Map, opts v1.UpdateOptions) (result *v1alpha1.Map, err error) {
	result = &v1alpha1.Map{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("maps").
		Name(m.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(m).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *maps) UpdateStatus(ctx context.Context, m *v1alpha1.Map, opts v1.UpdateOptions) (result *v1alpha1.Map, err error) {
	result = &v1alpha1.Map{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("maps").
		Name(m.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(m).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the map and deletes it. Returns an error if one occurs.
func (c *maps) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("maps").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *maps) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("maps").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched map.
func (c *maps) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Map, err error) {
	result = &v1alpha1.Map{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("maps").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
