apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../default
  - ../certmanager
  - ../webhook
patchesStrategicMerge:
  - manager_webhook_patch.yaml
  - webhook_cainjection_patch.yaml
vars:
  - fieldref:
      fieldPath: metadata.namespace
    name: CERTIFICATE_NAMESPACE
    objref:
      group: cert-manager.io
      kind: Certificate
      name: serving-cert
      version: v1
  - fieldref: { }
    name: CERTIFICATE_NAME
    objref:
      group: cert-manager.io
      kind: Certificate
      name: serving-cert
      version: v1
  - fieldref:
      fieldPath: metadata.namespace
    name: SERVICE_NAMESPACE
    objref:
      kind: Service
      name: webhook-service
      version: v1
  - fieldref: { }
    name: SERVICE_NAME
    objref:
      kind: Service
      name: webhook-service
      version: v1
