FROM golang:1.19
RUN go install github.com/go-delve/delve/cmd/dlv@latest
WORKDIR /
ADD bin/tilt/manager-debug manager-debug
ENTRYPOINT ["$GOPATH/bin/dlv --listen=:40000 --api-version=2 --headless=true exec /manager-debug"]
