- op: add
  path: "/spec/template/spec/containers/0/ports"
  value:
    - containerPort: 40000
- op: remove
  path: "/spec/template/spec/containers/0/livenessProbe"
- op: remove
  path: "/spec/template/spec/containers/0/readinessProbe"
