- op: add
  path: "/spec/template/spec/containers/0/env/-"
  value:
    name: "DEVELOPER_MODE_ENABLED"
    value: "true"
- op: remove
  path: "/spec/template/spec/containers/0/livenessProbe"
- op: remove
  path: "/spec/template/spec/containers/0/readinessProbe"
