apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
- manifests.yaml
- service.yaml

configurations:
- kustomizeconfig.yaml

patchesStrategicMerge:
- webhook_objectselector_patch.yaml
