apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "hazelcast-platform-operator.fullname" . }}
  labels:
    {{- include "hazelcast-platform-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
    - ""
  resources:
    - endpoints
    - nodes
    - pods
    - services
  verbs:
    - get
    - list
- apiGroups:
    - admissionregistration.k8s.io
  resources:
    - validatingwebhookconfigurations
  verbs:
    - get
    - list
    - update
    - watch
- apiGroups:
    - rbac.authorization.k8s.io
  resources:
    - clusterrolebindings
    - clusterroles
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
