{{- $watchAllNamespaces := (has (include "watched-namespaces.string" .) (list "" "*" )) -}}
{{- if .Values.createClusterScopedResources }}
{{- if or .Values.enableHazelcastNodeDiscovery $watchAllNamespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "hazelcast-platform-operator.fullname" . }}
  labels:
    {{- include "hazelcast-platform-operator.labels" . | nindent 4 }}
rules:
{{- if .Values.enableHazelcastNodeDiscovery }}
{{- include "hazelcast-platform-operator.hazelcastNodeReadRules" . | nindent 0 }}
{{- end }}
{{- if $watchAllNamespaces }}
{{- include "hazelcast-platform-operator.watchedNamespaceRules" . | nindent 0  }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "hazelcast-platform-operator.fullname" . }}
  labels:
    {{- include "hazelcast-platform-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "hazelcast-platform-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "hazelcast-platform-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- end -}}
