apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hazelcast-platform-operator.fullname" . }}
  labels:
    {{- include "hazelcast-platform-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "hazelcast-platform-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "hazelcast-platform-operator.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "hazelcast-platform-operator.serviceAccountName" . }}
      terminationGracePeriodSeconds: 10
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      # TODO: Add if check
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - emptyDir: { }
          name: cert
      containers:
        - command:
          - /manager
          args:
          - --leader-elect=false
          name: manager
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "hazelcast-platform-operator.imageName" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
            {{- if .Values.debug.enabled }}
            - containerPort: {{ .Values.debug.port }}
            {{- end }}
          {{- if not .Values.debug.enabled }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          {{- end }}
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: WATCH_NAMESPACE
              value: {{ .Values.watchNamespace }}
            - name: DEVELOPER_MODE_ENABLED
              value: {{ .Values.developerModeEnabled | quote }}
            - name: PHONE_HOME_ENABLED
              value: {{ .Values.phoneHomeEnabled | quote }}
