apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hazelcast-platform-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hazelcast-platform-operator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "hazelcast-platform-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "hazelcast-platform-operator.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "hazelcast-platform-operator.serviceAccountName" . }}
      terminationGracePeriodSeconds: 10
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- if .Values.webhook.enabled }}
      - name: cert
        secret:
          defaultMode: 420
          secretName: {{ include "hazelcast-platform-operator.fullname" . }}
      {{- end }}
      containers:
        - command:
          - /manager
          args:
          - --leader-elect=false
          name: manager
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ include "hazelcast-platform-operator.imageName" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- if .Values.webhook.enabled }}
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
            {{- end }}
            {{- if .Values.debug.enabled }}
            - containerPort: {{ .Values.debug.port }}
            {{- end }}
          {{- if not .Values.debug.enabled }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          {{- end }}
          volumeMounts:
            {{- if .Values.webhook.enabled }}
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: WATCHED_NAMESPACES
              value: {{ include "watched-namespaces.string" . | quote }}
            - name: HAZELCAST_NODE_DISCOVERY_ENABLED
              value: {{ .Values.enableHazelcastNodeDiscovery | quote }}
            - name: DEVELOPER_MODE_ENABLED
              value: {{ .Values.developerModeEnabled | quote }}
            - name: PHONE_HOME_ENABLED
              value: {{ .Values.phoneHomeEnabled | quote }}
