apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "hazelcast-platform-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hazelcast-platform-operator.labels" . | nindent 4 }}
rules:
{{- include "hazelcast-platform-operator.operatorNamespaceRules" . | nindent 0  }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "hazelcast-platform-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hazelcast-platform-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "hazelcast-platform-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "hazelcast-platform-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
