apiVersion: v1
kind: Service
metadata:
  name: {{ include "hazelcast-platform-operator.fullname" . }}
  labels:
    {{- include "hazelcast-platform-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    {{- include "hazelcast-platform-operator.selectorLabels" . | nindent 4 }}
