# permissions for end users to edit caches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cache-editor-role
rules:
- apiGroups:
  - hazelcast.com
  resources:
  - caches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hazelcast.com
  resources:
  - caches/status
  verbs:
  - get
