# permissions for end users to view managementcenters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: managementcenter-viewer-role
rules:
- apiGroups:
  - hazelcast.com
  resources:
  - managementcenters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hazelcast.com
  resources:
  - managementcenters/status
  verbs:
  - get
