apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterrolebindings
      - clusterroles
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manager-role
  namespace: operator-namespace
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manager-role
  namespace: watched
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - events
      - pods
      - secrets
      - serviceaccounts
      - services
      - endpoints
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - hazelcast.com
    resources:
      - caches
      - cronhotbackups
      - hazelcastendpoints
      - hazelcasts
      - hotbackups
      - jetjobs
      - jetjobsnapshots
      - managementcenters
      - maps
      - multimaps
      - queues
      - replicatedmaps
      - topics
      - usercodenamespaces
      - wansyncs
      - wanreplications
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - hazelcast.com
    resources:
      - caches/finalizers
      - cronhotbackups/finalizers
      - hazelcastendpoints/finalizers
      - hazelcasts/finalizers
      - hotbackups/finalizers
      - jetjobs/finalizers
      - jetjobsnapshots/finalizers
      - managementcenters/finalizers
      - maps/finalizers
      - multimaps/finalizers
      - queues/finalizers
      - replicatedmaps/finalizers
      - topics/finalizers
      - usercodenamespaces/finalizers
      - wansyncs/finalizers
      - wanreplications/finalizers
    verbs:
      - update
  - apiGroups:
      - hazelcast.com
    resources:
      - caches/status
      - cronhotbackups/status
      - hazelcastendpoints/status
      - hazelcasts/status
      - hotbackups/status
      - jetjobs/status
      - jetjobsnapshots/status
      - managementcenters/status
      - maps/status
      - multimaps/status
      - queues/status
      - replicatedmaps/status
      - topics/status
      - usercodenamespaces/status
      - wansyncs/status
      - wanreplications/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
      - roles
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - route.openshift.io
    resources:
      - routes/custom-host
    verbs:
      - create
  - apiGroups:
      - route.openshift.io
    resources:
      - routes/status
    verbs:
      - get
