apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: hazelcast-sample
spec:
  clusterSize: 3
  repository: 'docker.io/hazelcast/hazelcast-enterprise'
  licenseKeySecretName: hazelcast-license-key
  jet:
    enabled: true
    resourceUploadEnabled: true
    bucketConfig:
      bucketURI: "gs://operator-user-code/jetJobs"
      secretName: br-secret-gcp
---
apiVersion: hazelcast.com/v1alpha1
kind: JetJob
metadata:
  name: jet-job-sample
spec:
  hazelcastResourceName: hazelcast
  state: Running
  jarName: jet-pipeline-1.0.2.jar
---
apiVersion: hazelcast.com/v1alpha1
kind: JetJob
metadata:
  name: jet-job-longrun
spec:
  hazelcastResourceName: hazelcast
  state: Running
  jarName: jet-pipeline-longrun-2.0.0.jar
