apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: hazelcast
spec:
  version: '5.3.5'
  exposeExternally:
    type: Unisocket
    discoveryServiceType: LoadBalancer
  jet:
    enabled: true
    resourceUploadEnabled: true
    bucketConfig:
      bucketURI: "gs://operator-user-code/jetJobs"
      secretName: br-secret-gcp
