apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: hazelcast
spec:
  userCodeDeployment:
    bucketConfig:
      secretName: br-secret-gcp
      bucketURI: "gs://operator-custom-class/executorService"
  executorServices:
    - name: service1
      userCodeNamespace: my-ucn-is-not-here
  durableExecutorServices:
    - name: service2
  scheduledExecutorServices:
    - name: service3