apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: hazelcast
spec:
  userCodeDeployment:
    bucketConfig:
      secret: br-secret-gcp
      bucketURI: "gs://operator-user-code/entryListener"
