apiVersion: hazelcast.com/v1alpha1
kind: JetJob
metadata:
  labels:
    app.kubernetes.io/name: jetjob
    app.kubernetes.io/instance: jetjob-sample
    app.kubernetes.io/part-of: hazelcast-platform-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: hazelcast-platform-operator
  name: jet-job-sample
spec:
  name: my-test-jet-job
  hazelcastResourceName: hazelcast
  state: Running
  jarName: jet-pipeline-1.0.2.jar
  bucketConfig:
    bucketURI: "gs://operator-user-code/jetJobs"
    secret: br-secret-gcp

