apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: hazelcast
spec:
  customClass:
    secret: br-secret-gcp
    bucketURI: "gs://operator-custom-class/executorService"
  executorServices:
    basicExecutorServices:
      - name: service1

