apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: hazelcast
spec:
  clusterSize: 3
  repository: "docker.io/hazelcast/hazelcast-enterprise"
  licenseKeySecretName: hazelcast-license-key
  agent:
    repository: hazelcast/platform-operator-agent
  persistence:
    clusterDataRecoveryPolicy: "FullRecoveryOnly"
    pvc:
      accessModes: ["ReadWriteOnce"]
      requestStorage: 8Gi
    restore:
      bucketConfig:
        secretName: br-secret-az
        bucketURI: "azblob://backup?prefix=hazelcast/2022-06-02-21-57-49/"
