apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: hazelcast
spec:
  userCodeDeployment:
    enabled: true
    bucketConfig:
      secret: cc-secret
      bucketURI: "gs://userCodeDeployment"
