//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcknowledgementSetting) DeepCopyInto(out *AcknowledgementSetting) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcknowledgementSetting.
func (in *AcknowledgementSetting) DeepCopy() *AcknowledgementSetting {
	if in == nil {
		return nil
	}
	out := new(AcknowledgementSetting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdvancedNetwork) DeepCopyInto(out *AdvancedNetwork) {
	*out = *in
	in.MemberServerSocketEndpointConfig.DeepCopyInto(&out.MemberServerSocketEndpointConfig)
	in.ClientServerSocketEndpointConfig.DeepCopyInto(&out.ClientServerSocketEndpointConfig)
	if in.WAN != nil {
		in, out := &in.WAN, &out.WAN
		*out = make([]WANConfig, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdvancedNetwork.
func (in *AdvancedNetwork) DeepCopy() *AdvancedNetwork {
	if in == nil {
		return nil
	}
	out := new(AdvancedNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentConfiguration) DeepCopyInto(out *AgentConfiguration) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentConfiguration.
func (in *AgentConfiguration) DeepCopy() *AgentConfiguration {
	if in == nil {
		return nil
	}
	out := new(AgentConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttributeConfig) DeepCopyInto(out *AttributeConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttributeConfig.
func (in *AttributeConfig) DeepCopy() *AttributeConfig {
	if in == nil {
		return nil
	}
	out := new(AttributeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BatchSetting) DeepCopyInto(out *BatchSetting) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BatchSetting.
func (in *BatchSetting) DeepCopy() *BatchSetting {
	if in == nil {
		return nil
	}
	out := new(BatchSetting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitmapIndexOptionsConfig) DeepCopyInto(out *BitmapIndexOptionsConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitmapIndexOptionsConfig.
func (in *BitmapIndexOptionsConfig) DeepCopy() *BitmapIndexOptionsConfig {
	if in == nil {
		return nil
	}
	out := new(BitmapIndexOptionsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BucketConfiguration) DeepCopyInto(out *BucketConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BucketConfiguration.
func (in *BucketConfiguration) DeepCopy() *BucketConfiguration {
	if in == nil {
		return nil
	}
	out := new(BucketConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPSubsystem) DeepCopyInto(out *CPSubsystem) {
	*out = *in
	if in.SessionTTLSeconds != nil {
		in, out := &in.SessionTTLSeconds, &out.SessionTTLSeconds
		*out = new(int32)
		**out = **in
	}
	if in.SessionHeartbeatIntervalSeconds != nil {
		in, out := &in.SessionHeartbeatIntervalSeconds, &out.SessionHeartbeatIntervalSeconds
		*out = new(int32)
		**out = **in
	}
	if in.MissingCpMemberAutoRemovalSeconds != nil {
		in, out := &in.MissingCpMemberAutoRemovalSeconds, &out.MissingCpMemberAutoRemovalSeconds
		*out = new(int32)
		**out = **in
	}
	if in.FailOnIndeterminateOperationState != nil {
		in, out := &in.FailOnIndeterminateOperationState, &out.FailOnIndeterminateOperationState
		*out = new(bool)
		**out = **in
	}
	if in.DataLoadTimeoutSeconds != nil {
		in, out := &in.DataLoadTimeoutSeconds, &out.DataLoadTimeoutSeconds
		*out = new(int32)
		**out = **in
	}
	if in.PVC != nil {
		in, out := &in.PVC, &out.PVC
		*out = new(PvcConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPSubsystem.
func (in *CPSubsystem) DeepCopy() *CPSubsystem {
	if in == nil {
		return nil
	}
	out := new(CPSubsystem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cache) DeepCopyInto(out *Cache) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cache.
func (in *Cache) DeepCopy() *Cache {
	if in == nil {
		return nil
	}
	out := new(Cache)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Cache) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheList) DeepCopyInto(out *CacheList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Cache, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheList.
func (in *CacheList) DeepCopy() *CacheList {
	if in == nil {
		return nil
	}
	out := new(CacheList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CacheList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheSpec) DeepCopyInto(out *CacheSpec) {
	*out = *in
	in.DataStructureSpec.DeepCopyInto(&out.DataStructureSpec)
	if in.EventJournal != nil {
		in, out := &in.EventJournal, &out.EventJournal
		*out = new(EventJournal)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheSpec.
func (in *CacheSpec) DeepCopy() *CacheSpec {
	if in == nil {
		return nil
	}
	out := new(CacheSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheStatus) DeepCopyInto(out *CacheStatus) {
	*out = *in
	in.DataStructureStatus.DeepCopyInto(&out.DataStructureStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheStatus.
func (in *CacheStatus) DeepCopy() *CacheStatus {
	if in == nil {
		return nil
	}
	out := new(CacheStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompactSerializationConfig) DeepCopyInto(out *CompactSerializationConfig) {
	*out = *in
	if in.Serializers != nil {
		in, out := &in.Serializers, &out.Serializers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Classes != nil {
		in, out := &in.Classes, &out.Classes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompactSerializationConfig.
func (in *CompactSerializationConfig) DeepCopy() *CompactSerializationConfig {
	if in == nil {
		return nil
	}
	out := new(CompactSerializationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronHotBackup) DeepCopyInto(out *CronHotBackup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronHotBackup.
func (in *CronHotBackup) DeepCopy() *CronHotBackup {
	if in == nil {
		return nil
	}
	out := new(CronHotBackup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CronHotBackup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronHotBackupList) DeepCopyInto(out *CronHotBackupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CronHotBackup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronHotBackupList.
func (in *CronHotBackupList) DeepCopy() *CronHotBackupList {
	if in == nil {
		return nil
	}
	out := new(CronHotBackupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CronHotBackupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronHotBackupSpec) DeepCopyInto(out *CronHotBackupSpec) {
	*out = *in
	in.HotBackupTemplate.DeepCopyInto(&out.HotBackupTemplate)
	if in.SuccessfulHotBackupsHistoryLimit != nil {
		in, out := &in.SuccessfulHotBackupsHistoryLimit, &out.SuccessfulHotBackupsHistoryLimit
		*out = new(int32)
		**out = **in
	}
	if in.FailedHotBackupsHistoryLimit != nil {
		in, out := &in.FailedHotBackupsHistoryLimit, &out.FailedHotBackupsHistoryLimit
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronHotBackupSpec.
func (in *CronHotBackupSpec) DeepCopy() *CronHotBackupSpec {
	if in == nil {
		return nil
	}
	out := new(CronHotBackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronHotBackupStatus) DeepCopyInto(out *CronHotBackupStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronHotBackupStatus.
func (in *CronHotBackupStatus) DeepCopy() *CronHotBackupStatus {
	if in == nil {
		return nil
	}
	out := new(CronHotBackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataStructureSpec) DeepCopyInto(out *DataStructureSpec) {
	*out = *in
	if in.BackupCount != nil {
		in, out := &in.BackupCount, &out.BackupCount
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataStructureSpec.
func (in *DataStructureSpec) DeepCopy() *DataStructureSpec {
	if in == nil {
		return nil
	}
	out := new(DataStructureSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataStructureStatus) DeepCopyInto(out *DataStructureStatus) {
	*out = *in
	if in.MemberStatuses != nil {
		in, out := &in.MemberStatuses, &out.MemberStatuses
		*out = make(map[string]DataStructureConfigState, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataStructureStatus.
func (in *DataStructureStatus) DeepCopy() *DataStructureStatus {
	if in == nil {
		return nil
	}
	out := new(DataStructureStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DurableExecutorServiceConfiguration) DeepCopyInto(out *DurableExecutorServiceConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DurableExecutorServiceConfiguration.
func (in *DurableExecutorServiceConfiguration) DeepCopy() *DurableExecutorServiceConfiguration {
	if in == nil {
		return nil
	}
	out := new(DurableExecutorServiceConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntryListenerConfiguration) DeepCopyInto(out *EntryListenerConfiguration) {
	*out = *in
	if in.IncludeValues != nil {
		in, out := &in.IncludeValues, &out.IncludeValues
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntryListenerConfiguration.
func (in *EntryListenerConfiguration) DeepCopy() *EntryListenerConfiguration {
	if in == nil {
		return nil
	}
	out := new(EntryListenerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventJournal) DeepCopyInto(out *EventJournal) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventJournal.
func (in *EventJournal) DeepCopy() *EventJournal {
	if in == nil {
		return nil
	}
	out := new(EventJournal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvictionConfig) DeepCopyInto(out *EvictionConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvictionConfig.
func (in *EvictionConfig) DeepCopy() *EvictionConfig {
	if in == nil {
		return nil
	}
	out := new(EvictionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecutorServiceConfiguration) DeepCopyInto(out *ExecutorServiceConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecutorServiceConfiguration.
func (in *ExecutorServiceConfiguration) DeepCopy() *ExecutorServiceConfiguration {
	if in == nil {
		return nil
	}
	out := new(ExecutorServiceConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExposeExternallyConfiguration) DeepCopyInto(out *ExposeExternallyConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExposeExternallyConfiguration.
func (in *ExposeExternallyConfiguration) DeepCopy() *ExposeExternallyConfiguration {
	if in == nil {
		return nil
	}
	out := new(ExposeExternallyConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalConnectivityConfiguration) DeepCopyInto(out *ExternalConnectivityConfiguration) {
	*out = *in
	if in.Ingress != nil {
		in, out := &in.Ingress, &out.Ingress
		*out = new(ExternalConnectivityIngress)
		(*in).DeepCopyInto(*out)
	}
	if in.Route != nil {
		in, out := &in.Route, &out.Route
		*out = new(ExternalConnectivityRoute)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalConnectivityConfiguration.
func (in *ExternalConnectivityConfiguration) DeepCopy() *ExternalConnectivityConfiguration {
	if in == nil {
		return nil
	}
	out := new(ExternalConnectivityConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalConnectivityIngress) DeepCopyInto(out *ExternalConnectivityIngress) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalConnectivityIngress.
func (in *ExternalConnectivityIngress) DeepCopy() *ExternalConnectivityIngress {
	if in == nil {
		return nil
	}
	out := new(ExternalConnectivityIngress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalConnectivityRoute) DeepCopyInto(out *ExternalConnectivityRoute) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalConnectivityRoute.
func (in *ExternalConnectivityRoute) DeepCopy() *ExternalConnectivityRoute {
	if in == nil {
		return nil
	}
	out := new(ExternalConnectivityRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalSerializer) DeepCopyInto(out *GlobalSerializer) {
	*out = *in
	if in.OverrideJavaSerialization != nil {
		in, out := &in.OverrideJavaSerialization, &out.OverrideJavaSerialization
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalSerializer.
func (in *GlobalSerializer) DeepCopy() *GlobalSerializer {
	if in == nil {
		return nil
	}
	out := new(GlobalSerializer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Hazelcast) DeepCopyInto(out *Hazelcast) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Hazelcast.
func (in *Hazelcast) DeepCopy() *Hazelcast {
	if in == nil {
		return nil
	}
	out := new(Hazelcast)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Hazelcast) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HazelcastClusterConfig) DeepCopyInto(out *HazelcastClusterConfig) {
	*out = *in
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLS)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HazelcastClusterConfig.
func (in *HazelcastClusterConfig) DeepCopy() *HazelcastClusterConfig {
	if in == nil {
		return nil
	}
	out := new(HazelcastClusterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HazelcastClusterStatus) DeepCopyInto(out *HazelcastClusterStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HazelcastClusterStatus.
func (in *HazelcastClusterStatus) DeepCopy() *HazelcastClusterStatus {
	if in == nil {
		return nil
	}
	out := new(HazelcastClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HazelcastEndpoint) DeepCopyInto(out *HazelcastEndpoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HazelcastEndpoint.
func (in *HazelcastEndpoint) DeepCopy() *HazelcastEndpoint {
	if in == nil {
		return nil
	}
	out := new(HazelcastEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HazelcastEndpoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HazelcastEndpointList) DeepCopyInto(out *HazelcastEndpointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HazelcastEndpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HazelcastEndpointList.
func (in *HazelcastEndpointList) DeepCopy() *HazelcastEndpointList {
	if in == nil {
		return nil
	}
	out := new(HazelcastEndpointList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HazelcastEndpointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HazelcastEndpointSpec) DeepCopyInto(out *HazelcastEndpointSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HazelcastEndpointSpec.
func (in *HazelcastEndpointSpec) DeepCopy() *HazelcastEndpointSpec {
	if in == nil {
		return nil
	}
	out := new(HazelcastEndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HazelcastEndpointStatus) DeepCopyInto(out *HazelcastEndpointStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HazelcastEndpointStatus.
func (in *HazelcastEndpointStatus) DeepCopy() *HazelcastEndpointStatus {
	if in == nil {
		return nil
	}
	out := new(HazelcastEndpointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HazelcastList) DeepCopyInto(out *HazelcastList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Hazelcast, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HazelcastList.
func (in *HazelcastList) DeepCopy() *HazelcastList {
	if in == nil {
		return nil
	}
	out := new(HazelcastList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HazelcastList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HazelcastMemberStatus) DeepCopyInto(out *HazelcastMemberStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HazelcastMemberStatus.
func (in *HazelcastMemberStatus) DeepCopy() *HazelcastMemberStatus {
	if in == nil {
		return nil
	}
	out := new(HazelcastMemberStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HazelcastPersistenceConfiguration) DeepCopyInto(out *HazelcastPersistenceConfiguration) {
	*out = *in
	if in.PVC != nil {
		in, out := &in.PVC, &out.PVC
		*out = new(PvcConfiguration)
		(*in).DeepCopyInto(*out)
	}
	in.Restore.DeepCopyInto(&out.Restore)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HazelcastPersistenceConfiguration.
func (in *HazelcastPersistenceConfiguration) DeepCopy() *HazelcastPersistenceConfiguration {
	if in == nil {
		return nil
	}
	out := new(HazelcastPersistenceConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HazelcastSpec) DeepCopyInto(out *HazelcastSpec) {
	*out = *in
	if in.ClusterSize != nil {
		in, out := &in.ClusterSize, &out.ClusterSize
		*out = new(int32)
		**out = **in
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.ExposeExternally != nil {
		in, out := &in.ExposeExternally, &out.ExposeExternally
		*out = new(ExposeExternallyConfiguration)
		**out = **in
	}
	if in.Scheduling != nil {
		in, out := &in.Scheduling, &out.Scheduling
		*out = new(SchedulingConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Persistence != nil {
		in, out := &in.Persistence, &out.Persistence
		*out = new(HazelcastPersistenceConfiguration)
		(*in).DeepCopyInto(*out)
	}
	in.Agent.DeepCopyInto(&out.Agent)
	if in.JetEngineConfiguration != nil {
		in, out := &in.JetEngineConfiguration, &out.JetEngineConfiguration
		*out = new(JetEngineConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.DeprecatedUserCodeDeployment != nil {
		in, out := &in.DeprecatedUserCodeDeployment, &out.DeprecatedUserCodeDeployment
		*out = new(UserCodeDeploymentConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ExecutorServices != nil {
		in, out := &in.ExecutorServices, &out.ExecutorServices
		*out = make([]ExecutorServiceConfiguration, len(*in))
		copy(*out, *in)
	}
	if in.DurableExecutorServices != nil {
		in, out := &in.DurableExecutorServices, &out.DurableExecutorServices
		*out = make([]DurableExecutorServiceConfiguration, len(*in))
		copy(*out, *in)
	}
	if in.ScheduledExecutorServices != nil {
		in, out := &in.ScheduledExecutorServices, &out.ScheduledExecutorServices
		*out = make([]ScheduledExecutorServiceConfiguration, len(*in))
		copy(*out, *in)
	}
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.JVM != nil {
		in, out := &in.JVM, &out.JVM
		*out = new(JVMConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.NativeMemory != nil {
		in, out := &in.NativeMemory, &out.NativeMemory
		*out = new(NativeMemoryConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.AdvancedNetwork != nil {
		in, out := &in.AdvancedNetwork, &out.AdvancedNetwork
		*out = new(AdvancedNetwork)
		(*in).DeepCopyInto(*out)
	}
	if in.ManagementCenterConfig != nil {
		in, out := &in.ManagementCenterConfig, &out.ManagementCenterConfig
		*out = new(ManagementCenterConfig)
		**out = **in
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLS)
		**out = **in
	}
	if in.Serialization != nil {
		in, out := &in.Serialization, &out.Serialization
		*out = new(SerializationConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SQL != nil {
		in, out := &in.SQL, &out.SQL
		*out = new(SQL)
		**out = **in
	}
	if in.LocalDevices != nil {
		in, out := &in.LocalDevices, &out.LocalDevices
		*out = make([]LocalDeviceConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.CPSubsystem != nil {
		in, out := &in.CPSubsystem, &out.CPSubsystem
		*out = new(CPSubsystem)
		(*in).DeepCopyInto(*out)
	}
	if in.UserCodeNamespaces != nil {
		in, out := &in.UserCodeNamespaces, &out.UserCodeNamespaces
		*out = new(UserCodeNamespacesConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HazelcastSpec.
func (in *HazelcastSpec) DeepCopy() *HazelcastSpec {
	if in == nil {
		return nil
	}
	out := new(HazelcastSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HazelcastStatus) DeepCopyInto(out *HazelcastStatus) {
	*out = *in
	out.Cluster = in.Cluster
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]HazelcastMemberStatus, len(*in))
		copy(*out, *in)
	}
	out.Restore = in.Restore
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HazelcastStatus.
func (in *HazelcastStatus) DeepCopy() *HazelcastStatus {
	if in == nil {
		return nil
	}
	out := new(HazelcastStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HotBackup) DeepCopyInto(out *HotBackup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HotBackup.
func (in *HotBackup) DeepCopy() *HotBackup {
	if in == nil {
		return nil
	}
	out := new(HotBackup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HotBackup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HotBackupList) DeepCopyInto(out *HotBackupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HotBackup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HotBackupList.
func (in *HotBackupList) DeepCopy() *HotBackupList {
	if in == nil {
		return nil
	}
	out := new(HotBackupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HotBackupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HotBackupSpec) DeepCopyInto(out *HotBackupSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HotBackupSpec.
func (in *HotBackupSpec) DeepCopy() *HotBackupSpec {
	if in == nil {
		return nil
	}
	out := new(HotBackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HotBackupStatus) DeepCopyInto(out *HotBackupStatus) {
	*out = *in
	if in.BackupUUIDs != nil {
		in, out := &in.BackupUUIDs, &out.BackupUUIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HotBackupStatus.
func (in *HotBackupStatus) DeepCopy() *HotBackupStatus {
	if in == nil {
		return nil
	}
	out := new(HotBackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HotBackupTemplateSpec) DeepCopyInto(out *HotBackupTemplateSpec) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HotBackupTemplateSpec.
func (in *HotBackupTemplateSpec) DeepCopy() *HotBackupTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(HotBackupTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IndexConfig) DeepCopyInto(out *IndexConfig) {
	*out = *in
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BitmapIndexOptions != nil {
		in, out := &in.BitmapIndexOptions, &out.BitmapIndexOptions
		*out = new(BitmapIndexOptionsConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IndexConfig.
func (in *IndexConfig) DeepCopy() *IndexConfig {
	if in == nil {
		return nil
	}
	out := new(IndexConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JVMConfiguration) DeepCopyInto(out *JVMConfiguration) {
	*out = *in
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(JVMMemoryConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.GC != nil {
		in, out := &in.GC, &out.GC
		*out = new(JVMGCConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JVMConfiguration.
func (in *JVMConfiguration) DeepCopy() *JVMConfiguration {
	if in == nil {
		return nil
	}
	out := new(JVMConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JVMGCConfiguration) DeepCopyInto(out *JVMGCConfiguration) {
	*out = *in
	if in.Logging != nil {
		in, out := &in.Logging, &out.Logging
		*out = new(bool)
		**out = **in
	}
	if in.Collector != nil {
		in, out := &in.Collector, &out.Collector
		*out = new(GCType)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JVMGCConfiguration.
func (in *JVMGCConfiguration) DeepCopy() *JVMGCConfiguration {
	if in == nil {
		return nil
	}
	out := new(JVMGCConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JVMMemoryConfiguration) DeepCopyInto(out *JVMMemoryConfiguration) {
	*out = *in
	if in.InitialRAMPercentage != nil {
		in, out := &in.InitialRAMPercentage, &out.InitialRAMPercentage
		*out = new(string)
		**out = **in
	}
	if in.MinRAMPercentage != nil {
		in, out := &in.MinRAMPercentage, &out.MinRAMPercentage
		*out = new(string)
		**out = **in
	}
	if in.MaxRAMPercentage != nil {
		in, out := &in.MaxRAMPercentage, &out.MaxRAMPercentage
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JVMMemoryConfiguration.
func (in *JVMMemoryConfiguration) DeepCopy() *JVMMemoryConfiguration {
	if in == nil {
		return nil
	}
	out := new(JVMMemoryConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JavaFilterConfig) DeepCopyInto(out *JavaFilterConfig) {
	*out = *in
	if in.Blacklist != nil {
		in, out := &in.Blacklist, &out.Blacklist
		*out = new(SerializationFilterList)
		(*in).DeepCopyInto(*out)
	}
	if in.Whitelist != nil {
		in, out := &in.Whitelist, &out.Whitelist
		*out = new(SerializationFilterList)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JavaFilterConfig.
func (in *JavaFilterConfig) DeepCopy() *JavaFilterConfig {
	if in == nil {
		return nil
	}
	out := new(JavaFilterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JetEdgeDefaults) DeepCopyInto(out *JetEdgeDefaults) {
	*out = *in
	if in.QueueSize != nil {
		in, out := &in.QueueSize, &out.QueueSize
		*out = new(int32)
		**out = **in
	}
	if in.PacketSizeLimit != nil {
		in, out := &in.PacketSizeLimit, &out.PacketSizeLimit
		*out = new(int32)
		**out = **in
	}
	if in.ReceiveWindowMultiplier != nil {
		in, out := &in.ReceiveWindowMultiplier, &out.ReceiveWindowMultiplier
		*out = new(int8)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JetEdgeDefaults.
func (in *JetEdgeDefaults) DeepCopy() *JetEdgeDefaults {
	if in == nil {
		return nil
	}
	out := new(JetEdgeDefaults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JetEngineConfiguration) DeepCopyInto(out *JetEngineConfiguration) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	in.RemoteFileConfiguration.DeepCopyInto(&out.RemoteFileConfiguration)
	if in.Instance != nil {
		in, out := &in.Instance, &out.Instance
		*out = new(JetInstance)
		(*in).DeepCopyInto(*out)
	}
	if in.EdgeDefaults != nil {
		in, out := &in.EdgeDefaults, &out.EdgeDefaults
		*out = new(JetEdgeDefaults)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JetEngineConfiguration.
func (in *JetEngineConfiguration) DeepCopy() *JetEngineConfiguration {
	if in == nil {
		return nil
	}
	out := new(JetEngineConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JetInstance) DeepCopyInto(out *JetInstance) {
	*out = *in
	if in.CooperativeThreadCount != nil {
		in, out := &in.CooperativeThreadCount, &out.CooperativeThreadCount
		*out = new(int32)
		**out = **in
	}
	if in.MaxProcessorAccumulatedRecords != nil {
		in, out := &in.MaxProcessorAccumulatedRecords, &out.MaxProcessorAccumulatedRecords
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JetInstance.
func (in *JetInstance) DeepCopy() *JetInstance {
	if in == nil {
		return nil
	}
	out := new(JetInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JetJob) DeepCopyInto(out *JetJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JetJob.
func (in *JetJob) DeepCopy() *JetJob {
	if in == nil {
		return nil
	}
	out := new(JetJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JetJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JetJobList) DeepCopyInto(out *JetJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]JetJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JetJobList.
func (in *JetJobList) DeepCopy() *JetJobList {
	if in == nil {
		return nil
	}
	out := new(JetJobList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JetJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JetJobSnapshot) DeepCopyInto(out *JetJobSnapshot) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JetJobSnapshot.
func (in *JetJobSnapshot) DeepCopy() *JetJobSnapshot {
	if in == nil {
		return nil
	}
	out := new(JetJobSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JetJobSnapshot) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JetJobSnapshotList) DeepCopyInto(out *JetJobSnapshotList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]JetJobSnapshot, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JetJobSnapshotList.
func (in *JetJobSnapshotList) DeepCopy() *JetJobSnapshotList {
	if in == nil {
		return nil
	}
	out := new(JetJobSnapshotList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JetJobSnapshotList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JetJobSnapshotSpec) DeepCopyInto(out *JetJobSnapshotSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JetJobSnapshotSpec.
func (in *JetJobSnapshotSpec) DeepCopy() *JetJobSnapshotSpec {
	if in == nil {
		return nil
	}
	out := new(JetJobSnapshotSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JetJobSnapshotStatus) DeepCopyInto(out *JetJobSnapshotStatus) {
	*out = *in
	if in.CreationTime != nil {
		in, out := &in.CreationTime, &out.CreationTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JetJobSnapshotStatus.
func (in *JetJobSnapshotStatus) DeepCopy() *JetJobSnapshotStatus {
	if in == nil {
		return nil
	}
	out := new(JetJobSnapshotStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JetJobSpec) DeepCopyInto(out *JetJobSpec) {
	*out = *in
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.JetRemoteFileConfiguration.DeepCopyInto(&out.JetRemoteFileConfiguration)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JetJobSpec.
func (in *JetJobSpec) DeepCopy() *JetJobSpec {
	if in == nil {
		return nil
	}
	out := new(JetJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JetJobStatus) DeepCopyInto(out *JetJobStatus) {
	*out = *in
	if in.SubmissionTime != nil {
		in, out := &in.SubmissionTime, &out.SubmissionTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JetJobStatus.
func (in *JetJobStatus) DeepCopy() *JetJobStatus {
	if in == nil {
		return nil
	}
	out := new(JetJobStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JetRemoteFileConfiguration) DeepCopyInto(out *JetRemoteFileConfiguration) {
	*out = *in
	if in.BucketConfiguration != nil {
		in, out := &in.BucketConfiguration, &out.BucketConfiguration
		*out = new(BucketConfiguration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JetRemoteFileConfiguration.
func (in *JetRemoteFileConfiguration) DeepCopy() *JetRemoteFileConfiguration {
	if in == nil {
		return nil
	}
	out := new(JetRemoteFileConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LDAPProvider) DeepCopyInto(out *LDAPProvider) {
	*out = *in
	if in.AdminGroups != nil {
		in, out := &in.AdminGroups, &out.AdminGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.UserGroups != nil {
		in, out := &in.UserGroups, &out.UserGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ReadonlyUserGroups != nil {
		in, out := &in.ReadonlyUserGroups, &out.ReadonlyUserGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MetricsOnlyGroups != nil {
		in, out := &in.MetricsOnlyGroups, &out.MetricsOnlyGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LDAPProvider.
func (in *LDAPProvider) DeepCopy() *LDAPProvider {
	if in == nil {
		return nil
	}
	out := new(LDAPProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalDeviceConfig) DeepCopyInto(out *LocalDeviceConfig) {
	*out = *in
	if in.BlockSize != nil {
		in, out := &in.BlockSize, &out.BlockSize
		*out = new(int32)
		**out = **in
	}
	if in.ReadIOThreadCount != nil {
		in, out := &in.ReadIOThreadCount, &out.ReadIOThreadCount
		*out = new(int32)
		**out = **in
	}
	if in.WriteIOThreadCount != nil {
		in, out := &in.WriteIOThreadCount, &out.WriteIOThreadCount
		*out = new(int32)
		**out = **in
	}
	if in.PVC != nil {
		in, out := &in.PVC, &out.PVC
		*out = new(PvcConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalDeviceConfig.
func (in *LocalDeviceConfig) DeepCopy() *LocalDeviceConfig {
	if in == nil {
		return nil
	}
	out := new(LocalDeviceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCJVMConfiguration) DeepCopyInto(out *MCJVMConfiguration) {
	*out = *in
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCJVMConfiguration.
func (in *MCJVMConfiguration) DeepCopy() *MCJVMConfiguration {
	if in == nil {
		return nil
	}
	out := new(MCJVMConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPersistenceConfiguration) DeepCopyInto(out *MCPersistenceConfiguration) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.StorageClass != nil {
		in, out := &in.StorageClass, &out.StorageClass
		*out = new(string)
		**out = **in
	}
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPersistenceConfiguration.
func (in *MCPersistenceConfiguration) DeepCopy() *MCPersistenceConfiguration {
	if in == nil {
		return nil
	}
	out := new(MCPersistenceConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementCenter) DeepCopyInto(out *ManagementCenter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementCenter.
func (in *ManagementCenter) DeepCopy() *ManagementCenter {
	if in == nil {
		return nil
	}
	out := new(ManagementCenter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagementCenter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementCenterConfig) DeepCopyInto(out *ManagementCenterConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementCenterConfig.
func (in *ManagementCenterConfig) DeepCopy() *ManagementCenterConfig {
	if in == nil {
		return nil
	}
	out := new(ManagementCenterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementCenterList) DeepCopyInto(out *ManagementCenterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ManagementCenter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementCenterList.
func (in *ManagementCenterList) DeepCopy() *ManagementCenterList {
	if in == nil {
		return nil
	}
	out := new(ManagementCenterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagementCenterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementCenterSpec) DeepCopyInto(out *ManagementCenterSpec) {
	*out = *in
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.HazelcastClusters != nil {
		in, out := &in.HazelcastClusters, &out.HazelcastClusters
		*out = make([]HazelcastClusterConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExternalConnectivity != nil {
		in, out := &in.ExternalConnectivity, &out.ExternalConnectivity
		*out = new(ExternalConnectivityConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Persistence != nil {
		in, out := &in.Persistence, &out.Persistence
		*out = new(MCPersistenceConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Scheduling != nil {
		in, out := &in.Scheduling, &out.Scheduling
		*out = new(SchedulingConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.JVM != nil {
		in, out := &in.JVM, &out.JVM
		*out = new(MCJVMConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.SecurityProviders != nil {
		in, out := &in.SecurityProviders, &out.SecurityProviders
		*out = new(SecurityProviders)
		(*in).DeepCopyInto(*out)
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementCenterSpec.
func (in *ManagementCenterSpec) DeepCopy() *ManagementCenterSpec {
	if in == nil {
		return nil
	}
	out := new(ManagementCenterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementCenterStatus) DeepCopyInto(out *ManagementCenterStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementCenterStatus.
func (in *ManagementCenterStatus) DeepCopy() *ManagementCenterStatus {
	if in == nil {
		return nil
	}
	out := new(ManagementCenterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Map) DeepCopyInto(out *Map) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Map.
func (in *Map) DeepCopy() *Map {
	if in == nil {
		return nil
	}
	out := new(Map)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Map) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MapList) DeepCopyInto(out *MapList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Map, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MapList.
func (in *MapList) DeepCopy() *MapList {
	if in == nil {
		return nil
	}
	out := new(MapList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MapList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MapSpec) DeepCopyInto(out *MapSpec) {
	*out = *in
	in.DataStructureSpec.DeepCopyInto(&out.DataStructureSpec)
	out.Eviction = in.Eviction
	if in.Indexes != nil {
		in, out := &in.Indexes, &out.Indexes
		*out = make([]IndexConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = make([]AttributeConfig, len(*in))
		copy(*out, *in)
	}
	if in.MapStore != nil {
		in, out := &in.MapStore, &out.MapStore
		*out = new(MapStoreConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.EntryListeners != nil {
		in, out := &in.EntryListeners, &out.EntryListeners
		*out = make([]EntryListenerConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NearCache != nil {
		in, out := &in.NearCache, &out.NearCache
		*out = new(NearCache)
		(*in).DeepCopyInto(*out)
	}
	if in.EventJournal != nil {
		in, out := &in.EventJournal, &out.EventJournal
		*out = new(EventJournal)
		**out = **in
	}
	if in.TieredStore != nil {
		in, out := &in.TieredStore, &out.TieredStore
		*out = new(TieredStore)
		(*in).DeepCopyInto(*out)
	}
	if in.MerkleTree != nil {
		in, out := &in.MerkleTree, &out.MerkleTree
		*out = new(MerkleTreeConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MapSpec.
func (in *MapSpec) DeepCopy() *MapSpec {
	if in == nil {
		return nil
	}
	out := new(MapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MapStatus) DeepCopyInto(out *MapStatus) {
	*out = *in
	if in.MemberStatuses != nil {
		in, out := &in.MemberStatuses, &out.MemberStatuses
		*out = make(map[string]MapConfigState, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MapStatus.
func (in *MapStatus) DeepCopy() *MapStatus {
	if in == nil {
		return nil
	}
	out := new(MapStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MapStoreConfig) DeepCopyInto(out *MapStoreConfig) {
	*out = *in
	if in.WriteCoealescing != nil {
		in, out := &in.WriteCoealescing, &out.WriteCoealescing
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MapStoreConfig.
func (in *MapStoreConfig) DeepCopy() *MapStoreConfig {
	if in == nil {
		return nil
	}
	out := new(MapStoreConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MerkleTreeConfig) DeepCopyInto(out *MerkleTreeConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MerkleTreeConfig.
func (in *MerkleTreeConfig) DeepCopy() *MerkleTreeConfig {
	if in == nil {
		return nil
	}
	out := new(MerkleTreeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiMap) DeepCopyInto(out *MultiMap) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiMap.
func (in *MultiMap) DeepCopy() *MultiMap {
	if in == nil {
		return nil
	}
	out := new(MultiMap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MultiMap) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiMapList) DeepCopyInto(out *MultiMapList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MultiMap, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiMapList.
func (in *MultiMapList) DeepCopy() *MultiMapList {
	if in == nil {
		return nil
	}
	out := new(MultiMapList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MultiMapList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiMapSpec) DeepCopyInto(out *MultiMapSpec) {
	*out = *in
	in.DataStructureSpec.DeepCopyInto(&out.DataStructureSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiMapSpec.
func (in *MultiMapSpec) DeepCopy() *MultiMapSpec {
	if in == nil {
		return nil
	}
	out := new(MultiMapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiMapStatus) DeepCopyInto(out *MultiMapStatus) {
	*out = *in
	in.DataStructureStatus.DeepCopyInto(&out.DataStructureStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiMapStatus.
func (in *MultiMapStatus) DeepCopy() *MultiMapStatus {
	if in == nil {
		return nil
	}
	out := new(MultiMapStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NativeMemoryConfiguration) DeepCopyInto(out *NativeMemoryConfiguration) {
	*out = *in
	out.Size = in.Size.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NativeMemoryConfiguration.
func (in *NativeMemoryConfiguration) DeepCopy() *NativeMemoryConfiguration {
	if in == nil {
		return nil
	}
	out := new(NativeMemoryConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NearCache) DeepCopyInto(out *NearCache) {
	*out = *in
	if in.InvalidateOnChange != nil {
		in, out := &in.InvalidateOnChange, &out.InvalidateOnChange
		*out = new(bool)
		**out = **in
	}
	out.NearCacheEviction = in.NearCacheEviction
	if in.CacheLocalEntries != nil {
		in, out := &in.CacheLocalEntries, &out.CacheLocalEntries
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NearCache.
func (in *NearCache) DeepCopy() *NearCache {
	if in == nil {
		return nil
	}
	out := new(NearCache)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NearCacheEviction) DeepCopyInto(out *NearCacheEviction) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NearCacheEviction.
func (in *NearCacheEviction) DeepCopy() *NearCacheEviction {
	if in == nil {
		return nil
	}
	out := new(NearCacheEviction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PvcConfiguration) DeepCopyInto(out *PvcConfiguration) {
	*out = *in
	if in.AccessModes != nil {
		in, out := &in.AccessModes, &out.AccessModes
		*out = make([]v1.PersistentVolumeAccessMode, len(*in))
		copy(*out, *in)
	}
	if in.RequestStorage != nil {
		in, out := &in.RequestStorage, &out.RequestStorage
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PvcConfiguration.
func (in *PvcConfiguration) DeepCopy() *PvcConfiguration {
	if in == nil {
		return nil
	}
	out := new(PvcConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Queue) DeepCopyInto(out *Queue) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Queue.
func (in *Queue) DeepCopy() *Queue {
	if in == nil {
		return nil
	}
	out := new(Queue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Queue) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueList) DeepCopyInto(out *QueueList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Queue, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueList.
func (in *QueueList) DeepCopy() *QueueList {
	if in == nil {
		return nil
	}
	out := new(QueueList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QueueList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueSetting) DeepCopyInto(out *QueueSetting) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueSetting.
func (in *QueueSetting) DeepCopy() *QueueSetting {
	if in == nil {
		return nil
	}
	out := new(QueueSetting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueSpec) DeepCopyInto(out *QueueSpec) {
	*out = *in
	in.DataStructureSpec.DeepCopyInto(&out.DataStructureSpec)
	if in.EmptyQueueTtlSeconds != nil {
		in, out := &in.EmptyQueueTtlSeconds, &out.EmptyQueueTtlSeconds
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueSpec.
func (in *QueueSpec) DeepCopy() *QueueSpec {
	if in == nil {
		return nil
	}
	out := new(QueueSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueStatus) DeepCopyInto(out *QueueStatus) {
	*out = *in
	in.DataStructureStatus.DeepCopyInto(&out.DataStructureStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueStatus.
func (in *QueueStatus) DeepCopy() *QueueStatus {
	if in == nil {
		return nil
	}
	out := new(QueueStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteFileConfiguration) DeepCopyInto(out *RemoteFileConfiguration) {
	*out = *in
	if in.BucketConfiguration != nil {
		in, out := &in.BucketConfiguration, &out.BucketConfiguration
		*out = new(BucketConfiguration)
		**out = **in
	}
	if in.ConfigMaps != nil {
		in, out := &in.ConfigMaps, &out.ConfigMaps
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RemoteURLs != nil {
		in, out := &in.RemoteURLs, &out.RemoteURLs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteFileConfiguration.
func (in *RemoteFileConfiguration) DeepCopy() *RemoteFileConfiguration {
	if in == nil {
		return nil
	}
	out := new(RemoteFileConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicatedMap) DeepCopyInto(out *ReplicatedMap) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicatedMap.
func (in *ReplicatedMap) DeepCopy() *ReplicatedMap {
	if in == nil {
		return nil
	}
	out := new(ReplicatedMap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReplicatedMap) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicatedMapList) DeepCopyInto(out *ReplicatedMapList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ReplicatedMap, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicatedMapList.
func (in *ReplicatedMapList) DeepCopy() *ReplicatedMapList {
	if in == nil {
		return nil
	}
	out := new(ReplicatedMapList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReplicatedMapList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicatedMapSpec) DeepCopyInto(out *ReplicatedMapSpec) {
	*out = *in
	if in.AsyncFillup != nil {
		in, out := &in.AsyncFillup, &out.AsyncFillup
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicatedMapSpec.
func (in *ReplicatedMapSpec) DeepCopy() *ReplicatedMapSpec {
	if in == nil {
		return nil
	}
	out := new(ReplicatedMapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicatedMapStatus) DeepCopyInto(out *ReplicatedMapStatus) {
	*out = *in
	in.DataStructureStatus.DeepCopyInto(&out.DataStructureStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicatedMapStatus.
func (in *ReplicatedMapStatus) DeepCopy() *ReplicatedMapStatus {
	if in == nil {
		return nil
	}
	out := new(ReplicatedMapStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSpec) DeepCopyInto(out *ResourceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSpec.
func (in *ResourceSpec) DeepCopy() *ResourceSpec {
	if in == nil {
		return nil
	}
	out := new(ResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreConfiguration) DeepCopyInto(out *RestoreConfiguration) {
	*out = *in
	if in.BucketConfiguration != nil {
		in, out := &in.BucketConfiguration, &out.BucketConfiguration
		*out = new(BucketConfiguration)
		**out = **in
	}
	if in.LocalConfiguration != nil {
		in, out := &in.LocalConfiguration, &out.LocalConfiguration
		*out = new(RestoreFromLocalConfiguration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreConfiguration.
func (in *RestoreConfiguration) DeepCopy() *RestoreConfiguration {
	if in == nil {
		return nil
	}
	out := new(RestoreConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreFromLocalConfiguration) DeepCopyInto(out *RestoreFromLocalConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreFromLocalConfiguration.
func (in *RestoreFromLocalConfiguration) DeepCopy() *RestoreFromLocalConfiguration {
	if in == nil {
		return nil
	}
	out := new(RestoreFromLocalConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreStatus) DeepCopyInto(out *RestoreStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreStatus.
func (in *RestoreStatus) DeepCopy() *RestoreStatus {
	if in == nil {
		return nil
	}
	out := new(RestoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SQL) DeepCopyInto(out *SQL) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SQL.
func (in *SQL) DeepCopy() *SQL {
	if in == nil {
		return nil
	}
	out := new(SQL)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduledExecutorServiceConfiguration) DeepCopyInto(out *ScheduledExecutorServiceConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduledExecutorServiceConfiguration.
func (in *ScheduledExecutorServiceConfiguration) DeepCopy() *ScheduledExecutorServiceConfiguration {
	if in == nil {
		return nil
	}
	out := new(ScheduledExecutorServiceConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulingConfiguration) DeepCopyInto(out *SchedulingConfiguration) {
	*out = *in
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.TopologySpreadConstraints != nil {
		in, out := &in.TopologySpreadConstraints, &out.TopologySpreadConstraints
		*out = make([]v1.TopologySpreadConstraint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulingConfiguration.
func (in *SchedulingConfiguration) DeepCopy() *SchedulingConfiguration {
	if in == nil {
		return nil
	}
	out := new(SchedulingConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityProviders) DeepCopyInto(out *SecurityProviders) {
	*out = *in
	if in.LDAP != nil {
		in, out := &in.LDAP, &out.LDAP
		*out = new(LDAPProvider)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityProviders.
func (in *SecurityProviders) DeepCopy() *SecurityProviders {
	if in == nil {
		return nil
	}
	out := new(SecurityProviders)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SerializationConfig) DeepCopyInto(out *SerializationConfig) {
	*out = *in
	if in.DataSerializableFactories != nil {
		in, out := &in.DataSerializableFactories, &out.DataSerializableFactories
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PortableFactories != nil {
		in, out := &in.PortableFactories, &out.PortableFactories
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.GlobalSerializer != nil {
		in, out := &in.GlobalSerializer, &out.GlobalSerializer
		*out = new(GlobalSerializer)
		(*in).DeepCopyInto(*out)
	}
	if in.Serializers != nil {
		in, out := &in.Serializers, &out.Serializers
		*out = make([]Serializer, len(*in))
		copy(*out, *in)
	}
	if in.CompactSerialization != nil {
		in, out := &in.CompactSerialization, &out.CompactSerialization
		*out = new(CompactSerializationConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.JavaSerializationFilter != nil {
		in, out := &in.JavaSerializationFilter, &out.JavaSerializationFilter
		*out = new(JavaFilterConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SerializationConfig.
func (in *SerializationConfig) DeepCopy() *SerializationConfig {
	if in == nil {
		return nil
	}
	out := new(SerializationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SerializationFilterList) DeepCopyInto(out *SerializationFilterList) {
	*out = *in
	if in.Classes != nil {
		in, out := &in.Classes, &out.Classes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Packages != nil {
		in, out := &in.Packages, &out.Packages
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Prefixes != nil {
		in, out := &in.Prefixes, &out.Prefixes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SerializationFilterList.
func (in *SerializationFilterList) DeepCopy() *SerializationFilterList {
	if in == nil {
		return nil
	}
	out := new(SerializationFilterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Serializer) DeepCopyInto(out *Serializer) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Serializer.
func (in *Serializer) DeepCopy() *Serializer {
	if in == nil {
		return nil
	}
	out := new(Serializer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerSocketEndpointConfig) DeepCopyInto(out *ServerSocketEndpointConfig) {
	*out = *in
	if in.Interfaces != nil {
		in, out := &in.Interfaces, &out.Interfaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerSocketEndpointConfig.
func (in *ServerSocketEndpointConfig) DeepCopy() *ServerSocketEndpointConfig {
	if in == nil {
		return nil
	}
	out := new(ServerSocketEndpointConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLS) DeepCopyInto(out *TLS) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLS.
func (in *TLS) DeepCopy() *TLS {
	if in == nil {
		return nil
	}
	out := new(TLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TieredStore) DeepCopyInto(out *TieredStore) {
	*out = *in
	if in.MemoryCapacity != nil {
		in, out := &in.MemoryCapacity, &out.MemoryCapacity
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TieredStore.
func (in *TieredStore) DeepCopy() *TieredStore {
	if in == nil {
		return nil
	}
	out := new(TieredStore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Topic) DeepCopyInto(out *Topic) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Topic.
func (in *Topic) DeepCopy() *Topic {
	if in == nil {
		return nil
	}
	out := new(Topic)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Topic) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopicList) DeepCopyInto(out *TopicList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Topic, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopicList.
func (in *TopicList) DeepCopy() *TopicList {
	if in == nil {
		return nil
	}
	out := new(TopicList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TopicList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopicSpec) DeepCopyInto(out *TopicSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopicSpec.
func (in *TopicSpec) DeepCopy() *TopicSpec {
	if in == nil {
		return nil
	}
	out := new(TopicSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopicStatus) DeepCopyInto(out *TopicStatus) {
	*out = *in
	in.DataStructureStatus.DeepCopyInto(&out.DataStructureStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopicStatus.
func (in *TopicStatus) DeepCopy() *TopicStatus {
	if in == nil {
		return nil
	}
	out := new(TopicStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserCodeDeploymentConfig) DeepCopyInto(out *UserCodeDeploymentConfig) {
	*out = *in
	if in.ClientEnabled != nil {
		in, out := &in.ClientEnabled, &out.ClientEnabled
		*out = new(bool)
		**out = **in
	}
	in.RemoteFileConfiguration.DeepCopyInto(&out.RemoteFileConfiguration)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserCodeDeploymentConfig.
func (in *UserCodeDeploymentConfig) DeepCopy() *UserCodeDeploymentConfig {
	if in == nil {
		return nil
	}
	out := new(UserCodeDeploymentConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserCodeNamespace) DeepCopyInto(out *UserCodeNamespace) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserCodeNamespace.
func (in *UserCodeNamespace) DeepCopy() *UserCodeNamespace {
	if in == nil {
		return nil
	}
	out := new(UserCodeNamespace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UserCodeNamespace) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserCodeNamespaceList) DeepCopyInto(out *UserCodeNamespaceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UserCodeNamespace, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserCodeNamespaceList.
func (in *UserCodeNamespaceList) DeepCopy() *UserCodeNamespaceList {
	if in == nil {
		return nil
	}
	out := new(UserCodeNamespaceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UserCodeNamespaceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserCodeNamespaceSpec) DeepCopyInto(out *UserCodeNamespaceSpec) {
	*out = *in
	if in.BucketConfiguration != nil {
		in, out := &in.BucketConfiguration, &out.BucketConfiguration
		*out = new(BucketConfiguration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserCodeNamespaceSpec.
func (in *UserCodeNamespaceSpec) DeepCopy() *UserCodeNamespaceSpec {
	if in == nil {
		return nil
	}
	out := new(UserCodeNamespaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserCodeNamespaceStatus) DeepCopyInto(out *UserCodeNamespaceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserCodeNamespaceStatus.
func (in *UserCodeNamespaceStatus) DeepCopy() *UserCodeNamespaceStatus {
	if in == nil {
		return nil
	}
	out := new(UserCodeNamespaceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserCodeNamespacesConfig) DeepCopyInto(out *UserCodeNamespacesConfig) {
	*out = *in
	if in.ClassFilter != nil {
		in, out := &in.ClassFilter, &out.ClassFilter
		*out = new(JavaFilterConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserCodeNamespacesConfig.
func (in *UserCodeNamespacesConfig) DeepCopy() *UserCodeNamespacesConfig {
	if in == nil {
		return nil
	}
	out := new(UserCodeNamespacesConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WANConfig) DeepCopyInto(out *WANConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WANConfig.
func (in *WANConfig) DeepCopy() *WANConfig {
	if in == nil {
		return nil
	}
	out := new(WANConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WanReplication) DeepCopyInto(out *WanReplication) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WanReplication.
func (in *WanReplication) DeepCopy() *WanReplication {
	if in == nil {
		return nil
	}
	out := new(WanReplication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WanReplication) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WanReplicationList) DeepCopyInto(out *WanReplicationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WanReplication, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WanReplicationList.
func (in *WanReplicationList) DeepCopy() *WanReplicationList {
	if in == nil {
		return nil
	}
	out := new(WanReplicationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WanReplicationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WanReplicationMapStatus) DeepCopyInto(out *WanReplicationMapStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WanReplicationMapStatus.
func (in *WanReplicationMapStatus) DeepCopy() *WanReplicationMapStatus {
	if in == nil {
		return nil
	}
	out := new(WanReplicationMapStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WanReplicationSpec) DeepCopyInto(out *WanReplicationSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]ResourceSpec, len(*in))
		copy(*out, *in)
	}
	out.Queue = in.Queue
	out.Batch = in.Batch
	out.Acknowledgement = in.Acknowledgement
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WanReplicationSpec.
func (in *WanReplicationSpec) DeepCopy() *WanReplicationSpec {
	if in == nil {
		return nil
	}
	out := new(WanReplicationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WanReplicationStatus) DeepCopyInto(out *WanReplicationStatus) {
	*out = *in
	if in.WanReplicationMapsStatus != nil {
		in, out := &in.WanReplicationMapsStatus, &out.WanReplicationMapsStatus
		*out = make(map[string]WanReplicationMapStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WanReplicationStatus.
func (in *WanReplicationStatus) DeepCopy() *WanReplicationStatus {
	if in == nil {
		return nil
	}
	out := new(WanReplicationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WanSync) DeepCopyInto(out *WanSync) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WanSync.
func (in *WanSync) DeepCopy() *WanSync {
	if in == nil {
		return nil
	}
	out := new(WanSync)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WanSync) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WanSyncList) DeepCopyInto(out *WanSyncList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WanSync, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WanSyncList.
func (in *WanSyncList) DeepCopy() *WanSyncList {
	if in == nil {
		return nil
	}
	out := new(WanSyncList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WanSyncList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WanSyncMapStatus) DeepCopyInto(out *WanSyncMapStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WanSyncMapStatus.
func (in *WanSyncMapStatus) DeepCopy() *WanSyncMapStatus {
	if in == nil {
		return nil
	}
	out := new(WanSyncMapStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WanSyncSpec) DeepCopyInto(out *WanSyncSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WanSyncSpec.
func (in *WanSyncSpec) DeepCopy() *WanSyncSpec {
	if in == nil {
		return nil
	}
	out := new(WanSyncSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WanSyncStatus) DeepCopyInto(out *WanSyncStatus) {
	*out = *in
	if in.WanSyncMapsStatus != nil {
		in, out := &in.WanSyncMapsStatus, &out.WanSyncMapsStatus
		*out = make(map[string]WanSyncMapStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WanSyncStatus.
func (in *WanSyncStatus) DeepCopy() *WanSyncStatus {
	if in == nil {
		return nil
	}
	out := new(WanSyncStatus)
	in.DeepCopyInto(out)
	return out
}
