//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdvancedNetwork) DeepCopyInto(out *AdvancedNetwork) {
	*out = *in
	in.MemberServerSocketEndpointConfig.DeepCopyInto(&out.MemberServerSocketEndpointConfig)
	if in.WAN != nil {
		in, out := &in.WAN, &out.WAN
		*out = make([]WANConfig, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdvancedNetwork.
func (in *AdvancedNetwork) DeepCopy() *AdvancedNetwork {
	if in == nil {
		return nil
	}
	out := new(AdvancedNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentConfiguration) DeepCopyInto(out *AgentConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentConfiguration.
func (in *AgentConfiguration) DeepCopy() *AgentConfiguration {
	if in == nil {
		return nil
	}
	out := new(AgentConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BucketConfiguration) DeepCopyInto(out *BucketConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BucketConfiguration.
func (in *BucketConfiguration) DeepCopy() *BucketConfiguration {
	if in == nil {
		return nil
	}
	out := new(BucketConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientServerSocketEndpointConfig) DeepCopyInto(out *ClientServerSocketEndpointConfig) {
	*out = *in
	if in.Interfaces != nil {
		in, out := &in.Interfaces, &out.Interfaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientServerSocketEndpointConfig.
func (in *ClientServerSocketEndpointConfig) DeepCopy() *ClientServerSocketEndpointConfig {
	if in == nil {
		return nil
	}
	out := new(ClientServerSocketEndpointConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DurableExecutorServiceConfiguration) DeepCopyInto(out *DurableExecutorServiceConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DurableExecutorServiceConfiguration.
func (in *DurableExecutorServiceConfiguration) DeepCopy() *DurableExecutorServiceConfiguration {
	if in == nil {
		return nil
	}
	out := new(DurableExecutorServiceConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecutorServiceConfiguration) DeepCopyInto(out *ExecutorServiceConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecutorServiceConfiguration.
func (in *ExecutorServiceConfiguration) DeepCopy() *ExecutorServiceConfiguration {
	if in == nil {
		return nil
	}
	out := new(ExecutorServiceConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExposeExternallyConfiguration) DeepCopyInto(out *ExposeExternallyConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExposeExternallyConfiguration.
func (in *ExposeExternallyConfiguration) DeepCopy() *ExposeExternallyConfiguration {
	if in == nil {
		return nil
	}
	out := new(ExposeExternallyConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Hazelcast) DeepCopyInto(out *Hazelcast) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Hazelcast.
func (in *Hazelcast) DeepCopy() *Hazelcast {
	if in == nil {
		return nil
	}
	out := new(Hazelcast)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Hazelcast) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HazelcastClusterStatus) DeepCopyInto(out *HazelcastClusterStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HazelcastClusterStatus.
func (in *HazelcastClusterStatus) DeepCopy() *HazelcastClusterStatus {
	if in == nil {
		return nil
	}
	out := new(HazelcastClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HazelcastList) DeepCopyInto(out *HazelcastList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Hazelcast, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HazelcastList.
func (in *HazelcastList) DeepCopy() *HazelcastList {
	if in == nil {
		return nil
	}
	out := new(HazelcastList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HazelcastList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HazelcastMemberStatus) DeepCopyInto(out *HazelcastMemberStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HazelcastMemberStatus.
func (in *HazelcastMemberStatus) DeepCopy() *HazelcastMemberStatus {
	if in == nil {
		return nil
	}
	out := new(HazelcastMemberStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HazelcastPersistenceConfiguration) DeepCopyInto(out *HazelcastPersistenceConfiguration) {
	*out = *in
	in.Pvc.DeepCopyInto(&out.Pvc)
	in.Restore.DeepCopyInto(&out.Restore)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HazelcastPersistenceConfiguration.
func (in *HazelcastPersistenceConfiguration) DeepCopy() *HazelcastPersistenceConfiguration {
	if in == nil {
		return nil
	}
	out := new(HazelcastPersistenceConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HazelcastSpec) DeepCopyInto(out *HazelcastSpec) {
	*out = *in
	if in.ClusterSize != nil {
		in, out := &in.ClusterSize, &out.ClusterSize
		*out = new(int32)
		**out = **in
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.ExposeExternally != nil {
		in, out := &in.ExposeExternally, &out.ExposeExternally
		*out = new(ExposeExternallyConfiguration)
		**out = **in
	}
	in.Scheduling.DeepCopyInto(&out.Scheduling)
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Persistence != nil {
		in, out := &in.Persistence, &out.Persistence
		*out = new(HazelcastPersistenceConfiguration)
		(*in).DeepCopyInto(*out)
	}
	out.Agent = in.Agent
	in.JetEngineConfiguration.DeepCopyInto(&out.JetEngineConfiguration)
	in.UserCodeDeployment.DeepCopyInto(&out.UserCodeDeployment)
	if in.ExecutorServices != nil {
		in, out := &in.ExecutorServices, &out.ExecutorServices
		*out = make([]ExecutorServiceConfiguration, len(*in))
		copy(*out, *in)
	}
	if in.DurableExecutorServices != nil {
		in, out := &in.DurableExecutorServices, &out.DurableExecutorServices
		*out = make([]DurableExecutorServiceConfiguration, len(*in))
		copy(*out, *in)
	}
	if in.ScheduledExecutorServices != nil {
		in, out := &in.ScheduledExecutorServices, &out.ScheduledExecutorServices
		*out = make([]ScheduledExecutorServiceConfiguration, len(*in))
		copy(*out, *in)
	}
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.JVM != nil {
		in, out := &in.JVM, &out.JVM
		*out = new(JVMConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.NativeMemory != nil {
		in, out := &in.NativeMemory, &out.NativeMemory
		*out = new(NativeMemoryConfiguration)
		(*in).DeepCopyInto(*out)
	}
	in.AdvancedNetwork.DeepCopyInto(&out.AdvancedNetwork)
	out.ManagementCenterConfig = in.ManagementCenterConfig
	out.TLS = in.TLS
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HazelcastSpec.
func (in *HazelcastSpec) DeepCopy() *HazelcastSpec {
	if in == nil {
		return nil
	}
	out := new(HazelcastSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HazelcastStatus) DeepCopyInto(out *HazelcastStatus) {
	*out = *in
	out.Cluster = in.Cluster
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]HazelcastMemberStatus, len(*in))
		copy(*out, *in)
	}
	out.Restore = in.Restore
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HazelcastStatus.
func (in *HazelcastStatus) DeepCopy() *HazelcastStatus {
	if in == nil {
		return nil
	}
	out := new(HazelcastStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JVMConfiguration) DeepCopyInto(out *JVMConfiguration) {
	*out = *in
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(JVMMemoryConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.GC != nil {
		in, out := &in.GC, &out.GC
		*out = new(JVMGCConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JVMConfiguration.
func (in *JVMConfiguration) DeepCopy() *JVMConfiguration {
	if in == nil {
		return nil
	}
	out := new(JVMConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JVMGCConfiguration) DeepCopyInto(out *JVMGCConfiguration) {
	*out = *in
	if in.Logging != nil {
		in, out := &in.Logging, &out.Logging
		*out = new(bool)
		**out = **in
	}
	if in.Collector != nil {
		in, out := &in.Collector, &out.Collector
		*out = new(GCType)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JVMGCConfiguration.
func (in *JVMGCConfiguration) DeepCopy() *JVMGCConfiguration {
	if in == nil {
		return nil
	}
	out := new(JVMGCConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JVMMemoryConfiguration) DeepCopyInto(out *JVMMemoryConfiguration) {
	*out = *in
	if in.InitialRAMPercentage != nil {
		in, out := &in.InitialRAMPercentage, &out.InitialRAMPercentage
		*out = new(string)
		**out = **in
	}
	if in.MinRAMPercentage != nil {
		in, out := &in.MinRAMPercentage, &out.MinRAMPercentage
		*out = new(string)
		**out = **in
	}
	if in.MaxRAMPercentage != nil {
		in, out := &in.MaxRAMPercentage, &out.MaxRAMPercentage
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JVMMemoryConfiguration.
func (in *JVMMemoryConfiguration) DeepCopy() *JVMMemoryConfiguration {
	if in == nil {
		return nil
	}
	out := new(JVMMemoryConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JetEngineConfiguration) DeepCopyInto(out *JetEngineConfiguration) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.BucketConfiguration != nil {
		in, out := &in.BucketConfiguration, &out.BucketConfiguration
		*out = new(BucketConfiguration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JetEngineConfiguration.
func (in *JetEngineConfiguration) DeepCopy() *JetEngineConfiguration {
	if in == nil {
		return nil
	}
	out := new(JetEngineConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementCenterConfig) DeepCopyInto(out *ManagementCenterConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementCenterConfig.
func (in *ManagementCenterConfig) DeepCopy() *ManagementCenterConfig {
	if in == nil {
		return nil
	}
	out := new(ManagementCenterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemberServerSocketEndpointConfig) DeepCopyInto(out *MemberServerSocketEndpointConfig) {
	*out = *in
	if in.Interfaces != nil {
		in, out := &in.Interfaces, &out.Interfaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemberServerSocketEndpointConfig.
func (in *MemberServerSocketEndpointConfig) DeepCopy() *MemberServerSocketEndpointConfig {
	if in == nil {
		return nil
	}
	out := new(MemberServerSocketEndpointConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NativeMemoryConfiguration) DeepCopyInto(out *NativeMemoryConfiguration) {
	*out = *in
	out.Size = in.Size.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NativeMemoryConfiguration.
func (in *NativeMemoryConfiguration) DeepCopy() *NativeMemoryConfiguration {
	if in == nil {
		return nil
	}
	out := new(NativeMemoryConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistencePvcConfiguration) DeepCopyInto(out *PersistencePvcConfiguration) {
	*out = *in
	if in.AccessModes != nil {
		in, out := &in.AccessModes, &out.AccessModes
		*out = make([]v1.PersistentVolumeAccessMode, len(*in))
		copy(*out, *in)
	}
	if in.RequestStorage != nil {
		in, out := &in.RequestStorage, &out.RequestStorage
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistencePvcConfiguration.
func (in *PersistencePvcConfiguration) DeepCopy() *PersistencePvcConfiguration {
	if in == nil {
		return nil
	}
	out := new(PersistencePvcConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreConfiguration) DeepCopyInto(out *RestoreConfiguration) {
	*out = *in
	if in.BucketConfiguration != nil {
		in, out := &in.BucketConfiguration, &out.BucketConfiguration
		*out = new(BucketConfiguration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreConfiguration.
func (in *RestoreConfiguration) DeepCopy() *RestoreConfiguration {
	if in == nil {
		return nil
	}
	out := new(RestoreConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreStatus) DeepCopyInto(out *RestoreStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreStatus.
func (in *RestoreStatus) DeepCopy() *RestoreStatus {
	if in == nil {
		return nil
	}
	out := new(RestoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduledExecutorServiceConfiguration) DeepCopyInto(out *ScheduledExecutorServiceConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduledExecutorServiceConfiguration.
func (in *ScheduledExecutorServiceConfiguration) DeepCopy() *ScheduledExecutorServiceConfiguration {
	if in == nil {
		return nil
	}
	out := new(ScheduledExecutorServiceConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulingConfiguration) DeepCopyInto(out *SchedulingConfiguration) {
	*out = *in
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.TopologySpreadConstraints != nil {
		in, out := &in.TopologySpreadConstraints, &out.TopologySpreadConstraints
		*out = make([]v1.TopologySpreadConstraint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulingConfiguration.
func (in *SchedulingConfiguration) DeepCopy() *SchedulingConfiguration {
	if in == nil {
		return nil
	}
	out := new(SchedulingConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLS) DeepCopyInto(out *TLS) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLS.
func (in *TLS) DeepCopy() *TLS {
	if in == nil {
		return nil
	}
	out := new(TLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserCodeDeploymentConfig) DeepCopyInto(out *UserCodeDeploymentConfig) {
	*out = *in
	if in.ClientEnabled != nil {
		in, out := &in.ClientEnabled, &out.ClientEnabled
		*out = new(bool)
		**out = **in
	}
	if in.BucketConfiguration != nil {
		in, out := &in.BucketConfiguration, &out.BucketConfiguration
		*out = new(BucketConfiguration)
		**out = **in
	}
	if in.ConfigMaps != nil {
		in, out := &in.ConfigMaps, &out.ConfigMaps
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserCodeDeploymentConfig.
func (in *UserCodeDeploymentConfig) DeepCopy() *UserCodeDeploymentConfig {
	if in == nil {
		return nil
	}
	out := new(UserCodeDeploymentConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WANConfig) DeepCopyInto(out *WANConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WANConfig.
func (in *WANConfig) DeepCopy() *WANConfig {
	if in == nil {
		return nil
	}
	out := new(WANConfig)
	in.DeepCopyInto(out)
	return out
}
