name: auto-discovery-tests
on:
  workflow_dispatch:
  pull_request:
  
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  call-auto-discovery-workflow:
    uses: hazelcast/auto-discovery-test-suite/.github/workflows/aws-terraform-integration-tests.yml@main
    with:
      pr-number: ${{ github.event.pull_request.number }}
