name: (2) Start Release
on:
  workflow_dispatch:
  branch_protection_rule:
    - main


permissions:
  contents: write
  pull-requests: write

jobs:
  create_tag_and_package_chart:
    name: Create tag
    runs-on: ubuntu-latest
    steps:
      - name: Validate version
        run: |
          NUMBER='(0|[1-9][0-9]*)'
          RELEASE_VERSION=$( echo ${{ github.ref }} | cut -d '/' -f 3- )
          echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV
          
          #echo ${RELEASE_VERSION} | egrep "^$NUMBER.$NUMBER(.$NUMBER)?$"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Create a New Tag
        run: |
          TAG_VERSION=v${RELEASE_VERSION}
          git tag ${TAG_VERSION}
          git push origin ${TAG_VERSION}

      - name: Package operator chart and add it into index.yaml
        run: |
          helm package ./helm-charts/hazelcast-platform-operator
          helm package ./helm-charts/hazelcast-platform-operator/charts/hazelcast-platform-operator-crds

