name: (E2E) AWS Tests
on:
  workflow_dispatch:
  workflow_call:

env:
  AWS_REGION: us-east-1
  DELETE_EKS_STACK_TIMEOUT_IN_MINS: "15"
  GAR_REGION: us-east1
  GAR_PROJECT: hazelcast-33
  GAR_REPO: hazelcast-platform-operator
  NAMESPACE: test-operator-ee

jobs:
  prepare-env:
    name: Create EKS cluster
    runs-on: ubuntu-latest
    outputs:
      CLUSTER_NAME: ${{ steps.create-cluster.outputs.CLUSTER_NAME }}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install eksctl
        run: |-
          curl --silent --location \
            "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" \
            | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin

      - name: Create EKS cluster
        id: create-cluster
        run: |-
          CLUSTER_NAME="operator-e2e-test-eks-${GITHUB_SHA::8}-${{ github.run_number }}"
          echo "CLUSTER_NAME=${CLUSTER_NAME}" >> $GITHUB_ENV
          echo "CLUSTER_NAME=${CLUSTER_NAME}" >> $GITHUB_OUTPUT
          eksctl create cluster \
            --name "${CLUSTER_NAME}" \
            --region=${AWS_REGION} \
            --zones ${AWS_REGION}a \
            --zones ${AWS_REGION}c \
            --version auto \
            --with-oidc \
            --without-nodegroup

          eksctl create nodegroup \
            --cluster "${CLUSTER_NAME}" \
            --region=${AWS_REGION} \
            --name node-group-1 \
            --node-type t3a.2xlarge \
            --nodes 3 \
            --managed

          eksctl create addon \
            --name aws-ebs-csi-driver \
            --cluster "${CLUSTER_NAME}" \
            --region=${AWS_REGION}

      - name: Create IAM Service Account
        run: |
          ROLE_NAME="cn-test-iam-service-account-${{ github.run_number }}"

          eksctl create iamserviceaccount \
            --name aws-iam-sa \
            --namespace ${NAMESPACE} \
            --cluster ${CLUSTER_NAME} \
            --role-name ${ROLE_NAME}-ee \
            --attach-policy-arn arn:aws:iam::aws:policy/AmazonS3FullAccess \
            --approve

  grafana-setup:
    needs: [prepare-env]
    uses: ./.github/workflows/grafana-agent.yaml
    secrets: inherit
    with:
      cluster_name: ${{ needs.prepare-env.outputs.CLUSTER_NAME }}
      cluster_type: eks
      gh_run_id: ${{ github.run_id }}
      gh_run_number: ${{ github.run_number }}
      gh_sha: ${{ github.sha }}
      namespaces: "test-operator-ee"

  get-image:
    name: Get Image
    runs-on: ubuntu-latest
    outputs:
      IMG: ${{ steps.get-image-tag.outputs.IMG }}
    steps:
      - uses: actions/checkout@v4

      - name: Set Up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.3.0
        with:
          install: true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get Secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            GKE_SA_KEY,CN/GKE_SA_KEY

      - name: Authenticate to GAR
        uses: docker/login-action@v3
        with:
          registry: us-east1-docker.pkg.dev
          username: _json_key
          password: ${{ env.GKE_SA_KEY }}

      - name: Generate Image Name
        id: get-image-tag
        run: |
          echo "IMG=${{ env.GAR_REGION }}-docker.pkg.dev/${{ env.GAR_PROJECT }}/${{ env.GAR_REPO }}/$(uuidgen):5d" >> $GITHUB_OUTPUT

      - name: Build Image
        uses: docker/build-push-action@v6.2.0
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          build-args: |
            version=${{github.sha}}
            pardotID=dockerhub
          file: Dockerfile
          push: true
          tags: ${{ steps.get-image-tag.outputs.IMG }}
          cache-from: type=registry,ref=${{ env.GAR_REGION }}-docker.pkg.dev/${{ env.GAR_PROJECT }}/${{ env.GAR_REPO }}/${{ hashFiles('Dockerfile','main.go','api/**','controllers/**','internal/**','licenses/**','**/go.mod','**/go.sum') }}:14d
          cache-to: type=registry,ref=${{ env.GAR_REGION }}-docker.pkg.dev/${{ env.GAR_PROJECT }}/${{ env.GAR_REPO }}/${{ hashFiles('Dockerfile','main.go','api/**','controllers/**','internal/**','licenses/**','**/go.mod','**/go.sum') }}:14d

  eks-e2e-tests:
    name: Run e2e test on EKS
    runs-on: ubuntu-latest
    needs: ["prepare-env", "grafana-setup", "get-image"]
    defaults:
      run:
        shell: bash
    env:
      RELEASE_NAME: hp-ee-${{ github.run_id }}
      IMG: ${{ needs.get-image.outputs.IMG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.21.0"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get GH Public IP
        id: ip
        run: |
          response=$(curl -s canhazip.com)
          echo "ipv4=$response" >> "$GITHUB_OUTPUT"

      - name: Configure SecurityGroup of Nodes
        run: |-
          SECURITY_GROUP_ID=$(aws eks describe-cluster --region=${{ env.AWS_REGION }} --name=${{ needs.prepare-env.outputs.CLUSTER_NAME }} --query=cluster.resourcesVpcConfig.clusterSecurityGroupId --output=text --no-cli-pager)
          echo "SecurityGroupID: $SECURITY_GROUP_ID"

          aws ec2 authorize-security-group-ingress \
            --region=${AWS_REGION} \
            --group-id=${SECURITY_GROUP_ID} \
            --cidr=${{ steps.ip.outputs.ipv4 }}/32 \
            --protocol=tcp \
            --port=30000-32767

      - name: Get Secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            GKE_SA_KEY,CN/GKE_SA_KEY
            HZ_LICENSE_KEY,CN/HZ_LICENSE_KEY
            AZURE_STORAGE_KEY,CN/AZURE_STORAGE_KEY

      - name: Authenticate to GAR
        uses: docker/login-action@v3
        with:
          registry: us-east1-docker.pkg.dev
          username: _json_key
          password: ${{ env.GKE_SA_KEY }}

      - name: Update kubeconfig
        run: |-
          CLUSTER_NAME="operator-e2e-test-eks-${GITHUB_SHA::8}-${{ github.run_number }}"
          aws eks update-kubeconfig --name "${CLUSTER_NAME}"

      - name: Authenticate to GAR
        uses: docker/login-action@v3
        with:
          registry: us-east1-docker.pkg.dev
          username: _json_key
          password: ${{ env.GKE_SA_KEY }}

      - name: Install CRD's
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 1
          max_attempts: 2
          retry_on: error
          command: |
            make install-crds

      - name: Deploy Operator to EKS
        run: |
          kubectl config set-context --current --namespace=${NAMESPACE}
          DEPLOY_NAME=${RELEASE_NAME}-hazelcast-platform-operator
          make install-operator NAMESPACE=${NAMESPACE} IMG=${IMG} RELEASE_NAME=$RELEASE_NAME
          kubectl rollout status deployment $DEPLOY_NAME

      - name: Create secrets
        run: |
          kubectl create secret generic hazelcast-license-key \
            --namespace ${NAMESPACE} --from-literal=license-key=${{ env.HZ_LICENSE_KEY }}

          kubectl create secret generic br-secret-s3 --namespace ${NAMESPACE} \
            --from-literal=region=us-east-1 \
            --from-literal=access-key-id=${{ secrets.AWS_ACCESS_KEY_ID }} \
            --from-literal=secret-access-key=${{ secrets.AWS_SECRET_ACCESS_KEY }}

          kubectl create secret generic br-secret-az --namespace ${NAMESPACE} \
            --from-literal=storage-account=operatortest \
            --from-literal=storage-key=${{ env.AZURE_STORAGE_KEY }}
          
          kubectl create secret generic br-secret-gcp --namespace ${NAMESPACE} --from-literal=google-credentials-path='${{ env.GKE_SA_KEY }}'

      - name: Run Hazelcast E2E tests on EKS
        id: e2e-test
        run: |
          make test-e2e GO_TEST_FLAGS=-ee=true NAMESPACE=${NAMESPACE} RELEASE_NAME=${RELEASE_NAME} REPORT_SUFFIX=ee_01 WORKFLOW_ID=eks

      - name: Check if the operator pod has not restarted
        if: always()
        run: |
          source .github/scripts/utils.sh
          assert_operator_pod_not_restarted ${NAMESPACE}

      - name: Clean up after Tests
        if: always()
        run: |
          make clean-up-namespace NAMESPACE=${NAMESPACE}
          source .github/scripts/utils.sh
          wait_for_elb_deleted $DELETE_EKS_STACK_TIMEOUT_IN_MINS

      - name: Upload Test Report
        if: always() && github.event_name != 'workflow_dispatch'
        uses: actions/upload-artifact@v3
        with:
          name: test-report-eks
          path: allure-results/eks/

  update-test-run-status-badge:
    runs-on: ubuntu-latest
    needs: eks-e2e-tests
    if: always() && github.event_name != 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get Secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            GIST_CREATION_TOKEN,CN/GIST_CREATION_TOKEN
            TEST_STATUSES_GIST_ID,CN/TEST_STATUSES_GIST_ID

      - name: Update Status Badge
        run: |
          source .github/scripts/utils.sh
          update_status_badges ${{ github.run_id }} ${{ env.TEST_STATUSES_GIST_ID }} ${{ env.GIST_CREATION_TOKEN }}

  report-generation:
    needs: ["prepare-env", "eks-e2e-tests"]
    if: always() && (needs.eks-e2e-tests.result == 'success' || needs.eks-e2e-tests.result == 'failure') && github.event_name != 'workflow_dispatch'
    uses: ./.github/workflows/generate-test-report.yaml
    secrets: inherit
    with:
      WORKFLOW_ID: eks
      CLUSTER_NAME: ${{ needs.prepare-env.outputs.CLUSTER_NAME }}

  cleanup-namespaces:
    if: always()
    needs: ["prepare-env", "eks-e2e-tests"]
    uses: ./.github/workflows/cleanup-namespace.yaml
    secrets: inherit
    with:
      cluster_name: ${{ needs.prepare-env.outputs.CLUSTER_NAME }}
      cluster_type: eks
      namespaces: "test-operator-ee,grafana"

  delete-cluster:
    name: Delete EKS cluster
    runs-on: ubuntu-latest
    if: always()
    needs: ["prepare-env", "eks-e2e-tests", "cleanup-namespaces"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install eksctl
        run: |-
          curl --silent --location \
            "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" \
            | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin

      - name: Delete EKS cluster
        run: |-
          CLUSTER_NAME=${{ needs.prepare-env.outputs.CLUSTER_NAME }}
          REGION=${{ env.AWS_REGION }}
          eksctl delete cluster \
            --region=${REGION} \
            --name=${CLUSTER_NAME} \
            --wait

  slack_notify:
    name: Slack Notify
    needs: ["eks-e2e-tests", "delete-cluster"]
    if: always() && ( needs.eks-e2e-tests.result != 'success' || needs.delete-cluster.result != 'success')
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get Secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            SLACK_WEBHOOK_URL,CN/SLACK_WEBHOOK_URL

      - uses: 8398a7/action-slack@v3
        with:
          fields: repo,commit,author,action,eventName,workflow
          status: failure
          channel: "#github-actions-log"
        env:
          SLACK_WEBHOOK_URL: ${{ env.SLACK_WEBHOOK_URL }}
