name: (E2E) Azure Tests
on:
  workflow_dispatch:
  workflow_call:

env:
  AZURE_RESOURCE_GROUP: operator-test
  GAR_REGION: us-east1
  GAR_PROJECT: hazelcast-33
  GAR_REPO: hazelcast-platform-operator
  AWS_REGION: us-east-1

jobs:
  prepare-env:
    name: Create AKS cluster
    runs-on: ubuntu-latest
    outputs:
      CLUSTER_NAME: ${{ steps.create-cluster.outputs.CLUSTER_NAME }}
      NRG: ${{ steps.create-cluster.outputs.NRG }}
      NSG: ${{ steps.create-cluster.outputs.NSG }}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get Secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            AZURE_CREDENTIALS,CN/AZURE_CREDENTIALS

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}

      - name: Create AKS cluster
        id: create-cluster
        uses: azure/CLI@v2
        with:
          azcliversion: 2.31.0
          inlineScript: |
            CLUSTER_NAME="operator-e2e-test-${GITHUB_SHA::8}-${{ github.run_number }}"
            echo "CLUSTER_NAME=${CLUSTER_NAME}" >> $GITHUB_OUTPUT
            NRG=$(az aks create \
              --resource-group=${AZURE_RESOURCE_GROUP} \
              --name="${CLUSTER_NAME}" \
              --node-count=3 \
              --node-vm-size Standard_D4_v2 \
              --enable-node-public-ip \
              --generate-ssh-keys | jq -r .nodeResourceGroup)
            echo "NodeResourceGroup: ${NRG}"
            echo "NRG=${NRG}" >> $GITHUB_OUTPUT

            NSG=$(az network nsg list --resource-group=${NRG} --query='[0].name' --output=tsv)
            echo "NetworkSecurityGroup: ${NSG}"
            echo "NSG=${NSG}" >> $GITHUB_OUTPUT

            az network nsg rule create \
              --name=AllowExternalAccess \
              --nsg-name=${NSG} \
              --source-address-prefixes="192.0.2.0/24" \
              --priority=100 \
              --resource-group=${NRG} \
              --access=Allow \
              --destination-port-ranges=30000-32767 \
              --direction=Inbound \
              --protocol=Tcp

  grafana-setup:
    needs: [prepare-env]
    uses: ./.github/workflows/grafana-agent.yaml
    secrets: inherit
    with:
      cluster_name: ${{ needs.prepare-env.outputs.CLUSTER_NAME }}
      cluster_type: aks
      gh_run_id: ${{ github.run_id }}
      gh_run_number: ${{ github.run_number }}
      gh_sha: ${{ github.sha }}
      namespaces: "test-operator-os, test-operator-ee"

  get-image:
    name: Get Image
    runs-on: ubuntu-latest
    outputs:
      IMG: ${{ steps.get-image-tag.outputs.IMG }}
    steps:
      - uses: actions/checkout@v4

      - name: Set Up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.1.0
        with:
          install: true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get Secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            GKE_SA_KEY,CN/GKE_SA_KEY

      - name: Authenticate to GAR
        uses: docker/login-action@v3
        with:
          registry: us-east1-docker.pkg.dev
          username: _json_key
          password: ${{ env.GKE_SA_KEY }}

      - name: Generate Image Name
        id: get-image-tag
        run: |
          echo "IMG=${{ env.GAR_REGION }}-docker.pkg.dev/${{ env.GAR_PROJECT }}/${{ env.GAR_REPO }}/$(uuidgen):5d" >> $GITHUB_OUTPUT

      - name: Build Image
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          build-args: |
            version=${{github.sha}}
            pardotID=dockerhub
          file: Dockerfile
          push: true
          tags: ${{ steps.get-image-tag.outputs.IMG }}
          cache-from: type=registry,ref=${{ env.GAR_REGION }}-docker.pkg.dev/${{ env.GAR_PROJECT }}/${{ env.GAR_REPO }}/${{ hashFiles('Dockerfile','main.go','api/**','controllers/**','internal/**','licenses/**','**/go.mod','**/go.sum') }}:14d
          cache-to: type=registry,ref=${{ env.GAR_REGION }}-docker.pkg.dev/${{ env.GAR_PROJECT }}/${{ env.GAR_REPO }}/${{ hashFiles('Dockerfile','main.go','api/**','controllers/**','internal/**','licenses/**','**/go.mod','**/go.sum') }}:14d

  aks-e2e-tests:
    name: Run e2e test on AKS
    runs-on: ubuntu-latest
    needs: ["prepare-env", "grafana-setup", "get-image"]
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        edition: ["os", "ee"]
    env:
      NAMESPACE: test-operator-${{ matrix.edition }}
      IMG: ${{ needs.get-image.outputs.IMG }}
      RELEASE_NAME: hp-${{ matrix.edition }}-${{ github.run_id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.20.0"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get Secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            GKE_SA_KEY,CN/GKE_SA_KEY
            AZURE_CREDENTIALS,CN/AZURE_CREDENTIALS
            AZURE_STORAGE_KEY,CN/AZURE_STORAGE_KEY
            HZ_LICENSE_KEY,CN/HZ_LICENSE_KEY

      - name: Authenticate to GAR
        uses: docker/login-action@v3
        with:
          registry: us-east1-docker.pkg.dev
          username: _json_key
          password: ${{ env.GKE_SA_KEY }}

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}

      - name: Get GH Public IP
        id: ip
        uses: haythem/public-ip@v1.3

      - name: Update Network Security Group
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 1
          max_attempts: 3
          retry_on: error
          command: |
            az network nsg rule update \
              --name AllowExternalAccess \
              --nsg-name ${{ needs.prepare-env.outputs.NSG }} \
              --resource-group ${{ needs.prepare-env.outputs.NRG }} \
              --add sourceAddressPrefixes ${{ steps.ip.outputs.ipv4 }}/32

      - name: Update kubeconfig
        run: |-
          CLUSTER_NAME="operator-e2e-test-${GITHUB_SHA::8}-${{ github.run_number }}"
          az aks get-credentials --resource-group "${AZURE_RESOURCE_GROUP}" --name "${CLUSTER_NAME}"

      - name: Authenticate to GAR
        uses: docker/login-action@v3
        with:
          registry: us-east1-docker.pkg.dev
          username: _json_key
          password: ${{ env.GKE_SA_KEY }}

      - name: Deploy Operator to EKS
        run: |
          make install-crds
          kubectl create namespace ${NAMESPACE}
          kubectl config set-context --current --namespace=${NAMESPACE}

          DEPLOY_NAME=${RELEASE_NAME}-hazelcast-platform-operator
          make install-operator NAMESPACE=${NAMESPACE} IMG=${IMG} RELEASE_NAME=$RELEASE_NAME
          kubectl rollout status deployment $DEPLOY_NAME

      - name: Create secrets
        if: matrix.edition == 'ee'
        run: |
          kubectl create secret generic hazelcast-license-key --namespace ${NAMESPACE} \
            --from-literal=license-key=${{ env.HZ_LICENSE_KEY }}

          kubectl create secret generic br-secret-s3 --namespace ${NAMESPACE} \
            --from-literal=region=us-east-1 \
            --from-literal=access-key-id=${{ secrets.AWS_ACCESS_KEY_ID }} \
            --from-literal=secret-access-key=${{ secrets.AWS_SECRET_ACCESS_KEY }}

          kubectl create secret generic br-secret-az --namespace ${NAMESPACE} \
            --from-literal=storage-account=operatortest \
            --from-literal=storage-key=${{ env.AZURE_STORAGE_KEY }}

      - name: Create secret for both OS and EE tests
        run: |
          kubectl create secret generic br-secret-gcp --namespace ${NAMESPACE} --from-literal=google-credentials-path='${{ env.GKE_SA_KEY }}'

      - name: Run Hazelcast E2E tests on EKS
        id: e2e-test
        run: |
          case ${{ matrix.edition }} in
            os) GO_TEST_FLAGS=-ee=false;;
            ee) GO_TEST_FLAGS=-ee=true;;
            *)  echo Unexpected edition: ${{ matrix.edition }} && exit 1;;
          esac
          make test-e2e GO_TEST_FLAGS=${GO_TEST_FLAGS} NAMESPACE=${NAMESPACE} RELEASE_NAME=$RELEASE_NAME REPORT_SUFFIX=${{ matrix.edition }}_01 WORKFLOW_ID=aks

      - name: Clean up after Tests
        if: always()
        run: |
          make clean-up-namespace NAMESPACE=${NAMESPACE}

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-report-aks
          path: allure-results/aks/

  update-test-run-status-badge:
    runs-on: ubuntu-latest
    needs: aks-e2e-tests
    if: always() && github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get Secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            TEST_STATUSES_GIST_ID,CN/TEST_STATUSES_GIST_ID
            GIST_CREATION_TOKEN,CN/GIST_CREATION_TOKEN

      - name: Update Status Badge
        run: |
          source .github/scripts/utils.sh
          update_status_badges ${{ github.run_id }} ${{ env.TEST_STATUSES_GIST_ID }} ${{ env.GIST_CREATION_TOKEN }}

  report-generation:
    needs: ["prepare-env", "aks-e2e-tests"]
    if: always() && (needs.aks-e2e-tests.result == 'success' || needs.aks-e2e-tests.result == 'failure')
    uses: ./.github/workflows/generate-test-report.yaml
    secrets: inherit
    with:
      WORKFLOW_ID: aks
      CLUSTER_NAME: ${{ needs.prepare-env.outputs.CLUSTER_NAME }}

  cleanup-namespaces:
    if: always()
    needs: ["prepare-env", "aks-e2e-tests"]
    uses: ./.github/workflows/cleanup-namespace.yaml
    secrets: inherit
    with:
      cluster_name: ${{ needs.prepare-env.outputs.CLUSTER_NAME }}
      cluster_type: aks
      namespaces: "test-operator-os,test-operator-ee,grafana"

  delete-cluster:
    name: Delete AKS cluster
    runs-on: ubuntu-latest
    if: always()
    needs: ["prepare-env", "aks-e2e-tests", "cleanup-namespaces"]
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get Secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            AZURE_CREDENTIALS,CN/AZURE_CREDENTIALS

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}

      - name: Delete AKS cluster
        uses: azure/CLI@v2
        with:
          azcliversion: 2.31.0
          inlineScript: |
            CLUSTER_NAME="operator-e2e-test-${GITHUB_SHA::8}-${{ github.run_number }}"
            az aks delete --name "${CLUSTER_NAME}" --resource-group "${AZURE_RESOURCE_GROUP}" -y

  slack_notify:
    name: Slack Notify
    needs: ["aks-e2e-tests", "delete-cluster"]
    if: always() && ( needs.aks-e2e-tests.result != 'success' || needs.delete-cluster.result != 'success')
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get Secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            SLACK_WEBHOOK_URL,CN/SLACK_WEBHOOK_URL

      - uses: 8398a7/action-slack@v3
        with:
          fields: repo,commit,author,action,eventName,workflow
          status: failure
          channel: "#github-actions-log"
        env:
          SLACK_WEBHOOK_URL: ${{ env.SLACK_WEBHOOK_URL }}
