name: Install new relic on GKE
on:
  workflow_call:
    inputs:
      cluster_name:
        type: string
        required: true
      nr_cluster_name:
        type: string
        required: true
      gh_run_id:
        type: string
        required: true
      gh_run_number:
        type: string
        required: true
      gh_sha:
        type: string
        required: true
      gke_zone:
        type: string
        required: false
        default: 'europe-west1-b'
      gcp_project_id:
        type: string
        required: false
        default: 'hazelcast-33'
    secrets:
      GKE_SA_KEY:
        required: true
      NEW_RELIC_LICENCE_KEY:
        required: true
jobs:
  new-relic-setup:
    name: Setup New Relic agent
    env:
      NR_CLUSTER_NAME: ${{ inputs.nr_cluster_name }}
      CLUSTER_NAME: ${{ inputs.cluster_name }}
      GH_RUN_ID: ${{ inputs.gh_run_id }}
      GH_RUN_NUMBER: ${{ inputs.gh_run_number }}
      GH_SHA: ${{ inputs.gh_sha }}
      GKE_ZONE: ${{ inputs.gke_zone }}
      GCP_PROJECT_ID: ${{ inputs.gcp_project_id }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: "google-github-actions/auth@v0.8.1"
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      - name: Connect to the GKE cluster
        run: |
          gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} \
            --zone ${{ env.GKE_ZONE }} \
            --project ${{ env.GCP_PROJECT_ID }}

      - name: Install New Relic repo
        run: |
          helm repo add newrelic https://helm-charts.newrelic.com

      - name: Install New Relic agent
        run: |
          kubectl create namespace newrelic
          helm install --namespace=newrelic newrelic-bundle -f .github/newrelic/newrelic-values.yaml \
            --set "global.cluster=${{ env.NR_CLUSTER_NAME }}" \
            --set "global.licenseKey=${{ secrets.NEW_RELIC_LICENCE_KEY }}" \
            --set "newrelic-logging.fluentBit.additionalEnvVariables[0].name=K_CLUSTER_NAME,newrelic-logging.fluentBit.additionalEnvVariables[0].value=${{ env.CLUSTER_NAME }}" \
            --set "newrelic-logging.fluentBit.additionalEnvVariables[1].name=GITHUB_RUN_ID,newrelic-logging.fluentBit.additionalEnvVariables[1].value=\"${{ env.GH_RUN_ID }}\"" \
            --set "newrelic-logging.fluentBit.additionalEnvVariables[2].name=GITHUB_RUN_NUMBER,newrelic-logging.fluentBit.additionalEnvVariables[2].value=\"${{ env.GH_RUN_NUMBER }}\"" \
            --set "newrelic-logging.fluentBit.additionalEnvVariables[3].name=GITHUB_SHA,newrelic-logging.fluentBit.additionalEnvVariables[3].value=${{ env.GH_SHA }}" \
            --set "newrelic-logging.fluentBit.additionalEnvVariables[4].name=LOG_PARSER,newrelic-logging.fluentBit.additionalEnvVariables[4].value=cri" \
            newrelic/nri-bundle
