name: Nightly E2E tests on OCP
on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

env:
  NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}
  AWS_REGION: us-east-1
  RESTART_OCP_NODE_TIMEOUT: 15
  OCP_CLUSTER_URL: ${{ secrets.OCP_CLUSTER_URL }}
  OCP_USERNAME: ${{ secrets.OCP_USERNAME }}
  OCP_PASSWORD: ${{ secrets.OCP_PASSWORD }}

jobs:
  check-and-restart-nodes:
    name: Check OCP nodes state
    env:
      NR_CLUSTER_NAME: ocp-operator
      CLUSTER_NAME: api-demo-ocp4-hazelcast-com
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Restart Non-Ready Instances
        run: |
          source .github/scripts/utils.sh
          oc login ${OCP_CLUSTER_URL} -u=${OCP_USERNAME} -p=${OCP_PASSWORD} --insecure-skip-tls-verify
          wait_for_instance_restarted $RESTART_OCP_NODE_TIMEOUT

  new-relic-setup:
    name: Setup New Relic agent
    env:
      NR_CLUSTER_NAME: ocp-operator
      CLUSTER_NAME: api-demo-ocp4-hazelcast-com
    runs-on: ubuntu-latest
    needs: check-and-restart-nodes
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update kubeconfig
        run: |-
          oc login ${OCP_CLUSTER_URL} -u=${OCP_USERNAME} -p=${OCP_PASSWORD} --insecure-skip-tls-verify

      - name: Install New Relic repo
        run: |
          helm repo add newrelic https://helm-charts.newrelic.com

      - name: Install New Relic agent
        run: |
          kubectl create namespace newrelic || echo "namespace exists"
            oc adm policy add-scc-to-user privileged system:serviceaccount:newrelic:newrelic-bundle-nri-metadata-injection-admission
            oc adm policy add-scc-to-user privileged system:serviceaccount:newrelic:newrelic-bundle-newrelic-logging
            oc adm policy add-scc-to-user privileged system:serviceaccount:newrelic:newrelic-bundle-newrelic-infrastructure
            oc adm policy add-scc-to-user privileged system:serviceaccount:newrelic:newrelic-bundle-nri-kube-events
            oc adm policy add-scc-to-user privileged system:serviceaccount:newrelic:newrelic-bundle-nrk8s-controlplane
            oc adm policy add-scc-to-user privileged system:serviceaccount:newrelic:default

          helm install --namespace=newrelic newrelic-bundle -f .github/newrelic/newrelic-values.yaml \
            --set "global.cluster=${{ env.NR_CLUSTER_NAME }}" \
            --set "global.licenseKey=${{ secrets.NEW_RELIC_LICENCE_KEY }}" \
            --set "newrelic-logging.fluentBit.additionalEnvVariables[0].name=K_CLUSTER_NAME,newrelic-logging.fluentBit.additionalEnvVariables[0].value=${{ env.CLUSTER_NAME }}" \
            --set "newrelic-logging.fluentBit.additionalEnvVariables[1].name=GITHUB_RUN_ID,newrelic-logging.fluentBit.additionalEnvVariables[1].value=\"${{ github.run_id }}\"" \
            --set "newrelic-logging.fluentBit.additionalEnvVariables[2].name=GITHUB_RUN_NUMBER,newrelic-logging.fluentBit.additionalEnvVariables[2].value=\"${{ github.run_number }}\"" \
            --set "newrelic-logging.fluentBit.additionalEnvVariables[3].name=GITHUB_SHA,newrelic-logging.fluentBit.additionalEnvVariables[3].value=${{ github.sha }}" \
            --set "newrelic-logging.fluentBit.additionalEnvVariables[4].name=LOG_PARSER,newrelic-logging.fluentBit.additionalEnvVariables[4].value=cri" \
            newrelic/nri-bundle

  ocp-e2e-tests:
    name: Run e2e tests at OCP
    runs-on: ubuntu-latest
    needs: new-relic-setup
    strategy:
      fail-fast: false
      matrix:
        edition: [ 'os', 'ee' ]
    defaults:
      run:
        shell: bash
    env:
      IMG: hazelcast/hazelcast-platform-operator:latest-snapshot
      HZ_LICENSE_KEY: ${{ secrets.HZ_LICENSE_KEY }}
      NAMESPACE: oc-e2e-test-operator-nightly-${{ matrix.edition }}-${{ github.run_id }}
      NAME_PREFIX: hp-${{ matrix.edition }}-${{ github.run_id }}-
    steps:
      - name: Checkout to hazelcast-operator
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.19.0"

      - name: Cache Golang dependencies
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build Image
        if: github.event_name == 'workflow_dispatch'
        run: |
          IMG=ttl.sh/$(uuidgen):1h
          echo "IMG=${IMG}" >> $GITHUB_ENV

          make docker-build-ci IMG=$IMG VERSION=${{github.sha}}
          make docker-push IMG=$IMG

      - name: Update kubeconfig
        run: |-
            oc login ${OCP_CLUSTER_URL} -u=${OCP_USERNAME} -p=${OCP_PASSWORD} --insecure-skip-tls-verify

      - name: Deploy Hazelcast-Platform-Operator to OCP
        run: |
          oc new-project $NAMESPACE
          kubectl label namespace ${NAMESPACE} newrelic.com/scrape=true

          make deploy IMG=$IMG NAMESPACE=$NAMESPACE NAME_PREFIX=$NAME_PREFIX
          oc rollout status deployment ${NAME_PREFIX}controller-manager

      - name: Create secrets
        if: matrix.edition == 'ee'
        run: |
          kubectl create secret generic hazelcast-license-key \
            --namespace ${{ env.NAMESPACE }} \
            --from-literal=license-key=${{ secrets.HZ_LICENSE_KEY }}

          kubectl create secret generic br-secret-s3 --namespace ${NAMESPACE} \
            --from-literal=region=us-east-1 \
            --from-literal=access-key-id=${{ secrets.AWS_ACCESS_KEY_ID }} \
            --from-literal=secret-access-key=${{ secrets.AWS_SECRET_ACCESS_KEY }}

          kubectl create secret generic br-secret-az --namespace ${NAMESPACE} \
            --from-literal=storage-account=operatortest \
            --from-literal=storage-key=${{ secrets.AZURE_STORAGE_KEY }}

      - name: Create secret for both OS and EE tests
        run: |
          kubectl create secret generic br-secret-gcp --namespace ${NAMESPACE} --from-literal=google-credentials-path='${{ secrets.GKE_SA_KEY }}'

      - name: Run Hazelcast E2E tests at OCP
        id: e2e-test
        run: |
          case ${{ matrix.edition }} in
            os) GO_TEST_FLAGS=-ee=false;;
            ee) GO_TEST_FLAGS=-ee=true;;
            *)  echo Unexpected edition: ${{ matrix.edition }} && exit 1;;
          esac
          make test-e2e GO_TEST_FLAGS=${GO_TEST_FLAGS} NAMESPACE=$NAMESPACE NAME_PREFIX=$NAME_PREFIX WORKFLOW_ID=ocp
          echo "RUNNING TESTS in $NAMESPACE"

      - name: Clean up after Tests
        if: always()
        run: |
          make clean-up-namespace KUBECTL=oc NAMESPACE=${NAMESPACE}

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: allure-results/ocp/

  cleanup-unused-images-and-new-relic:
    name: Remove Unused Images From The Local Store
    runs-on: ubuntu-latest
    needs: ocp-e2e-tests
    if: always()
    steps:
      - name: Image Prune
        run: |
          oc login ${OCP_CLUSTER_URL} -u=${OCP_USERNAME} -p=${OCP_PASSWORD} --insecure-skip-tls-verify
          helm uninstall --namespace=newrelic newrelic-bundle
          kubectl delete namespace newrelic
          for NODE in $(oc get nodes --no-headers -o name); do
          oc debug ${NODE} -- chroot /host sh -c "sleep 5; podman image prune -a -f"
          done

  report-generation:
    needs: ocp-e2e-tests
    if: always() && (needs.ocp-e2e-tests.result == 'success' || needs.ocp-e2e-tests.result == 'failure')
    uses: ./.github/workflows/generate-test-report.yaml
    secrets: inherit
    with:
      WORKFLOW_ID: ocp

  slack_notify:
    name: Slack Notify
    needs: [ 'ocp-e2e-tests' ]
    if: always() &&  needs.ocp-e2e-tests.result != 'success' 
    runs-on: ubuntu-latest
    steps:
      - uses: 8398a7/action-slack@a189acbf0b7ea434558662ae25a0de71df69a435
        with:
          fields: repo,commit,author,action,eventName,workflow
          status: failure
          channel: "#github-actions-log"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
