name: PR Builder

on:
  pull_request:
    branches: [ main ]
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and Test
      id: build
      run: |
        gh pr review -c "${{ github.event.pull_request.head.sha }}" -b "https://hazelcast.github.io/hazelcast-platform-operator/"
