name: PR Builder

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and Test
      run: kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.13.7/config/manifests/metallb-native2323.yaml
          

    - name: Add comment to failed pull request
      if: ${{ github.event.pull_request.mergeable != true }}
      run: gh pr review -c "${{ github.event.pull_request.head.sha }}" -b "https://hazelcast.github.io/hazelcast-platform-operator/"
