name: Publish Hazelcast-Platform-Operator Helm chart

on:
  workflow_dispatch:
  push:
    paths:
      - "helm-charts/**"
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Package operator chart and add it into index.yaml
        run: |
          helm package ./helm-charts/hazelcast-platform-operator
          helm package ./helm-charts/hazelcast-platform-operator/charts/hazelcast-platform-operator-crds
          aws s3 cp s3://hazelcast-charts/index.yaml .
          helm repo index --url=https://hazelcast-charts.s3.amazonaws.com --merge ./index.yaml .

      - name: Push operator chart and index.yaml to S3 bucket
        run: |
          for CHART_TGZ in *.tgz; do aws s3 cp ${CHART_TGZ} s3://hazelcast-charts; done
          aws s3 cp ./index.yaml s3://hazelcast-charts