name: Pull Request
on:
  pull_request_target:
    types:
      - labeled
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"

env:
  GCP_PROJECT_ID: hazelcast-33
  GKE_ZONE: europe-west1-b

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  labeler:
    name: Add label to PR
    runs-on: ubuntu-latest
    steps:
    - name: Check Labels
      id: labeler
      uses: jimschubert/labeler-action@v2
      with:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
  linter:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3.2.0
        if: ${{ !cancelled() }}
        with:
          args: --timeout 3m --build-tags hazelcastinternal

      - name: Run yamllint
        uses: ibiqlik/action-yamllint@v3
        if: ${{ !cancelled() }}
        with:
          config_file: hack/yamllint.yaml

      - name: Check if bundle.yaml is updated
        run: |
          mv bundle.yaml bundle.yaml.old
          make generate-bundle-yaml

          if ! cmp -s bundle.yaml bundle.yaml.old; then
              echo "Please make sure your branch is up to date with main and run make generate-bundle-yaml"
              exit 1
          fi

