name: Pull Request Builder

on:
  pull_request_target:
    types:
      - labeled
    branches:
      - main
      - 'release/**'
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - main
      - 'release/**'
    paths-ignore:
      - "**.md"

env:
  GO_VERSION: '1.19.0'
  NR_OF_SUITES: 5
  GOBIN: ${{ github.workspace }}/bin

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linter:
    name: Run linters
    runs-on: ubuntu-latest
    permissions: {}
    if: ( !cancelled() && github.event_name == 'pull_request' )
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: ${{ format('>={0}', env.GO_VERSION) }}

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3.3.1
        if: ${{ !cancelled() }}
        with:
          args: --timeout 3m --build-tags hazelcastinternal

      - name: Run yamllint
        uses: ibiqlik/action-yamllint@v3
        if: ${{ !cancelled() }}
        with:
          config_file: hack/yamllint.yaml

      - name: Check if tests are unfocused
        if: ${{ !cancelled() }}
        run: |
           make ginkgo
           if [[ $($GOBIN/ginkgo unfocus | wc -l) -gt 1 ]]; then
             echo "Some tests have 'F' before the test name. Run the 'ginkgo unfocus' command against your branch '${{ github.event.pull_request.head.ref }}' and push the changes."
             exit 1
           fi

      - name: Check if bundle.yaml is updated
        run: |
          mv bundle.yaml bundle.yaml.old
          make generate-bundle-yaml

          if ! cmp -s bundle.yaml bundle.yaml.old; then
              echo "Please make sure your branch is up to date with main and run 'make generate-bundle-yaml'"
              exit 1
          fi

  unit-tests:
    name: Run unit and integration tests
    runs-on: ubuntu-latest
    permissions: {}
    if: ( !cancelled() && github.event_name == 'pull_request' )
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: ${{ format('>={0}', env.GO_VERSION) }}

      - name: Cache Golang dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run unit tests
        run: make test-unit

      - name: Run integration tests (OS)
        run: make GO_TEST_FLAGS="-ee=false" test-it

      - name: Run integration tests (EE)
        run: make GO_TEST_FLAGS="-ee=true" test-it

  generate-test-suites:
      name: Generate Test Suites
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - uses: actions/setup-go@v3
          with:
            go-version: ">=1.19.0"

        - name: Cache Golang dependencies
          uses: actions/cache@v3
          with:
            path: |
              ~/.cache/go-build
              ~/go/pkg/mod
            key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
            restore-keys: |
              ${{ runner.os }}-go-

        - name: Generate Test Suites
          id: set-outputs
          run: |
             source .github/scripts/utils.sh
             generate_test_suites $NR_OF_SUITES

        - name: Upload Test Suites
          uses: actions/upload-artifact@v3
          with:
            name: test-suites
            path: suite_files/

  get-image:
      name: Get Image
      runs-on: ubuntu-latest
      outputs:
        IMG: ${{ steps.build-img.outputs.IMG }}
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Build And Push Image
          id: build-img
          run: |
             IMG=ttl.sh/$(uuidgen):2h
             make docker-build-ci IMG=$IMG VERSION=${{github.sha}}
             make docker-push IMG=$IMG
             echo "IMG=${IMG}" >> $GITHUB_OUTPUT

  kind-e2e-tests:
    name: Run E2E tests
    runs-on: ubuntu-latest
    needs: [generate-test-suites, get-image]
    strategy:
      fail-fast: false
      matrix:
        node_number: ["01","02","03","04","05"]
        edition: ["os","ee"]
    if: >-
      ( !cancelled()
      && ((github.event_name == 'pull_request_target'
            && github.event.action == 'labeled'
            && github.event.label.name == 'safe-to-test'
            && github.event.pull_request.head.repo.full_name != github.repository)
          ||
          (github.event_name == 'pull_request'
            && github.event.pull_request.head.repo.full_name == github.repository))
      )
    env:
      NAMESPACE: kind-test-operator-nightly-${{ matrix.edition }}
      NAME_PREFIX: hp-${{ matrix.edition }}-${{ github.run_id }}-
      CLUSTER_NAME: kind
      IMG: ${{ needs.get-image.outputs.IMG }}
    steps:
      - name: Decide which ref to checkout
        id: decide-ref
        run: |
          if [[ "${{github.event_name}}" == "pull_request" ]]; then
            echo "ref=${{github.ref}}" >> $GITHUB_OUTPUT
          else
            echo "ref=refs/pull/${{ github.event.pull_request.number }}/merge" >> $GITHUB_OUTPUT
          fi

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{steps.decide-ref.outputs.ref}}

      - uses: actions/setup-go@v3
        with:
          go-version: ${{ format('>={0}', env.GO_VERSION) }}

      - name: Cache Golang dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Create Kind Config
        run: |
          cat <<EOT >> ./kind-config.yaml
          kind: Cluster
          apiVersion: kind.x-k8s.io/v1alpha4
          nodes:
          - role: control-plane
          - role: worker
          - role: worker
          - role: worker
          EOT

      - name: Create Kind Cluster
        uses: helm/kind-action@v1.5.0
        with:
          config: ./kind-config.yaml
          cluster_name: ${{ env.CLUSTER_NAME }}

      - name: Install Grafana Agent
        env:
          CLUSTER_TYPE: kind
          GH_RUN_ID: ${{ github.run_id }}
          GH_RUN_NUMBER: ${{ github.run_number }}
          GH_SHA: ${{ github.sha }}
          GRAFANA_REMOTE_WRITE_URL: ${{ secrets.GRAFANA_REMOTE_WRITE_URL }}
          LOKI_USERNAME: ${{ secrets.LOKI_USERNAME }}
          LOKI_PASSWORD: ${{ secrets.LOKI_PASSWORD }}
          GRAFANA_PROM_REMOTE_WRITE_URL: ${{ secrets.GRAFANA_PROM_REMOTE_WRITE_URL }}
          GRAFANA_PROM_USERNAME: ${{ secrets.GRAFANA_PROM_USERNAME }}
          GRAFANA_PROM_PASSWORD: ${{ secrets.GRAFANA_PROM_PASSWORD }}
          NAMESPACES: ${{ env.NAMESPACE }}
          GRAFANA_NS: grafana
        run: |
          kubectl create namespace ${GRAFANA_NS}
          NAMESPACE=${GRAFANA_NS} envsubst < .github/grafana/metrics-cm.yaml | /bin/sh -c 'kubectl apply -f -'
          NAMESPACE=${GRAFANA_NS} envsubst < .github/grafana/logs-cm.yaml | /bin/sh -c 'kubectl apply -f -'
          MANIFEST_URL=https://raw.githubusercontent.com/grafana/agent/v0.27.1/production/kubernetes/agent-bare.yaml NAMESPACE=${GRAFANA_NS} /bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/grafana/agent/v0.27.1/production/kubernetes/install-bare.sh)" | kubectl apply -f -
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts && helm repo update && \
          helm install ksm prometheus-community/kube-state-metrics --set image.tag=v2.4.2 -n ${GRAFANA_NS}
          MANIFEST_URL=https://raw.githubusercontent.com/grafana/agent/v0.27.1/production/kubernetes/agent-loki.yaml NAMESPACE=${GRAFANA_NS} /bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/grafana/agent/v0.27.1/production/kubernetes/install-bare.sh)" | kubectl apply -f -

      - name: Install metallb
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 3
          retry_on: error
          command: |
              kubectl create namespace ${NAMESPACE}
              kubectl config set-context --current --namespace=$NAMESPACE
              kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.13.7/config/manifests/metallb-native.yaml
              kubectl wait --for=condition=ready --timeout=60s -n metallb-system pod -l app=metallb
              HOST_MIN=$(docker network inspect -f '{{json .IPAM.Config}}' ${{ env.CLUSTER_NAME }} | jq -r '.[0].Subnet' |  sed  -n 's/.0.0.16/.255.200/p')
              HOST_MAX=$(docker network inspect -f '{{json .IPAM.Config}}' ${{ env.CLUSTER_NAME }} | jq -r '.[0].Subnet' |  sed  -n 's/.0.0.16/.255.250/p')
              IP_RANGE=$HOST_MIN-$HOST_MAX

              cat <<EOF | kubectl apply -f -
              apiVersion: metallb.io/v1beta1
              kind: IPAddressPool
              metadata:
                name: kind-pool
                namespace: metallb-system
              spec:
                addresses:
                - $IP_RANGE
              ---
              apiVersion: metallb.io/v1beta1
              kind: L2Advertisement
              metadata:
                name: l2
                namespace: metallb-system
              spec:
                ipAddressPools:
                - kind-pool
              EOF

      - name: Create Secrets
        if: matrix.edition == 'ee'
        run: |
          kubectl create secret generic hazelcast-license-key \
             --namespace ${{ env.NAMESPACE }} \
             --from-literal=license-key=${{ secrets.HZ_LICENSE_KEY }}

          kubectl create secret generic br-secret-s3 \
            --namespace ${{ env.NAMESPACE }} \
            --from-literal=region=us-east-1 \
            --from-literal=access-key-id=${{ secrets.AWS_ACCESS_KEY_ID }} \
            --from-literal=secret-access-key=${{ secrets.AWS_SECRET_ACCESS_KEY }}

          kubectl create secret generic br-secret-az \
            --namespace ${{ env.NAMESPACE }} \
            --from-literal=storage-account=operatortest \
            --from-literal=storage-key=${{ secrets.AZURE_STORAGE_KEY }}

      - name: Create Secret For Both OS and EE Tests
        run: |
          kubectl create secret generic br-secret-gcp \
          --namespace ${{ env.NAMESPACE }} \
          --from-literal=google-credentials-path='${{ secrets.GKE_SA_KEY }}'

      - name: Load Image
        run: |
          docker pull $IMG
          kind load docker-image $IMG --name ${{ env.CLUSTER_NAME }}

      - name: Deploy Operator to Kind Cluster
        run: |
          DEPLOY_NAME=${NAME_PREFIX}controller-manager
          make deploy IMG=$IMG NAMESPACE=$NAMESPACE NAME_PREFIX=$NAME_PREFIX
          kubectl rollout status deployment $DEPLOY_NAME

      - name: Download test-suites Files
        uses: actions/download-artifact@v3
        with:
          name: test-suites
          path: suite_files/

      - name: Run Tests
        id: e2e-test
        run: |
          case ${{ matrix.edition }} in
            os) GO_TEST_FLAGS=-ee=false;;
            ee) GO_TEST_FLAGS=-ee=true;;
            *)  echo Unexpected edition: ${{ matrix.edition }} && exit 1;;
          esac
          make test-e2e-split-kind REPORT_SUFFIX=${{ matrix.edition }}-${{ matrix.node_number }} GO_TEST_FLAGS=${GO_TEST_FLAGS} NAMESPACE=${NAMESPACE} NAME_PREFIX=${NAME_PREFIX} WORKFLOW_ID=pr FOCUSED_TESTS="$(cat suite_files/test_suite_${{ matrix.node_number }})"

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-report-pr
          path: allure-results/pr/

  report-generation:
    needs: ["kind-e2e-tests"]
    if: always() && (needs.kind-e2e-tests.result == 'success' || needs.kind-e2e-tests.result == 'failure')
    uses: ./.github/workflows/generate-test-report.yaml
    secrets: inherit
    with:
      WORKFLOW_ID: pr
      CLUSTER_NAME: kind