name: Pull Request
on:
  pull_request_target:
    types:
      - labeled
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"

env:
  GCP_PROJECT_ID: hazelcast-33
  GKE_ZONE: europe-west1-b

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  linter:
    name: Run linters
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Golang
        uses: actions/setup-go@v3
        with:
          go-version: "1.16"

  unit-tests:
    name: Run unit and integration tests
    runs-on: ubuntu-20.04
    needs: linter
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Golang
        uses: actions/setup-go@v3
        with:
          go-version: "1.16"

      - name: Cache Golang dependencies
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

  create-gke-cluster:
    name: Create GKE cluster and push image
    runs-on: ubuntu-20.04
    needs: unit-tests
    outputs:
      CLUSTER_NAME: ${{ steps.set-cluster-name.outputs.CLUSTER_NAME }}
    env:
      GCP_NETWORK: operator-test-network
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{steps.decide-ref.outputs.ref}}

      - name: Set up Golang
        uses: actions/setup-go@v3
        with:
          go-version: "1.16"

      - name: Cache Golang dependencies
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |

  gke-e2e-tests:
    name: Run E2E tests
    runs-on: ubuntu-20.04
    needs: create-gke-cluster
    if: always() && needs.create-gke-cluster.result == 'success'
    strategy:
      fail-fast: false
      matrix:
        edition: ["os", "ee"]
    env:
      NAMESPACE: test-operator-${{ matrix.edition }}
      KUBECTL_VERSION: 1.22.0
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{steps.decide-ref.outputs.ref}}

      - name: Set up Golang
        uses: actions/setup-go@v3
        with:
          go-version: "1.16"

      - name: Cache Golang dependencies
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run Hazelcast E2E tests at GKE
        id: e2e-test
        run: sleep 1000