name: Pull Request Builder
on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - main
      - 'release/**'
    paths-ignore:
      - "**.md"
  pull_request_target:
    types:
      - labeled
    branches:
      - main
      - 'release/**'
    paths-ignore:
      - "**.md"
jobs:
  hello:
    name: Hello
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo hello
