name: Wan Replication Tests
on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

env:
  GCP_PROJECT_ID: hazelcast-33
  GKE_ZONE: europe-west1-b
  NUMBER_OF_NODES: 2
  GCP_NETWORK: operator-test-network
  NAME_PREFIX: wan-ee-${{ github.run_id }}-

jobs:
  get-image:
    name: Get Image
    runs-on: ubuntu-20.04
    outputs:
      IMG: ${{ steps.build-img.outputs.IMG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build And Push Image To ttl.sh
        id: build-img
        run: |
          if [[ "${{github.event_name}}" == "workflow_dispatch" ]]; then
            IMG=ttl.sh/$(uuidgen):2h
            echo "::set-output name=IMG::${IMG}"
            make docker-build-ci IMG=$IMG VERSION=${{github.sha}}
            make docker-push IMG=$IMG
          else
            IMG=hazelcast/hazelcast-platform-operator:latest-snapshot
            echo "::set-output name=IMG::${IMG}"
          fi

  create-gke-cluster:
    name: Create GKE Cluster
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        cluster: ["first", "second"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Golang Dependencies
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Authenticate To ${{ matrix.cluster }} GCP Cluster
        uses: 'google-github-actions/auth@v0.8.0'
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      - name: Create ${{ matrix.cluster }} GKE Cluster
        id: set-cluster-data
        run: |-
          gcloud container clusters create ${{ matrix.cluster }}-wan-cluster-${GITHUB_RUN_NUMBER} \
            --zone=${{ env.GKE_ZONE }} \
            --project=${{ env.GCP_PROJECT_ID }} \
            --network=${{ env.GCP_NETWORK }} \
            --machine-type=n1-standard-16 \
            --num-nodes=${{ env.NUMBER_OF_NODES }}
          sleep 10

  deploy-operator:
    name: Deploy Hazelcast Operator
    needs: [create-gke-cluster, get-image]
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        cluster: ["first", "second"]
        namespace: ["first-ns", "second-ns"]
        exclude:
          - cluster: second
            namespace: second-ns
    env:
      IMG: ${{ needs.get-image.outputs.IMG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate To ${{ matrix.cluster }} GCP Cluster
        uses: 'google-github-actions/auth@v0.8.0'
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      - name: Connect To The ${{ matrix.cluster }} GKE Cluster
        run: |-
          gcloud container clusters get-credentials ${{ matrix.cluster }}-wan-cluster-${GITHUB_RUN_NUMBER} \
          --zone ${{ env.GKE_ZONE }} \
          --project ${{ env.GCP_PROJECT_ID }}

      - name: Deploy Operator To ${{ matrix.cluster }} GKE Cluster and ${{ matrix.namespace }} namespace
        run: |
          kubectl create namespace ${{ matrix.namespace }}
          kubectl label namespace ${{ matrix.namespace }} newrelic.com/scrape=true
          kubectl config set-context --current --namespace=${{ matrix.namespace }}
          DEPLOY_NAME=${NAME_PREFIX}controller-manager
          echo "DEPLOY_NAME=${DEPLOY_NAME}" >> $GITHUB_ENV
          make deploy IMG=$IMG NAMESPACE=${{ matrix.namespace }} NAME_PREFIX=$NAME_PREFIX
          kubectl rollout status deployment $DEPLOY_NAME

      - name: Create Secret On ${{ matrix.cluster }} Cluster and ${{ matrix.namespace }} namespace
        run: |
          kubectl create secret generic hazelcast-license-key \
            --namespace ${{ matrix.namespace }} \
            --from-literal=license-key=${{ secrets.HZ_LICENSE_KEY }}
