name: (2) Release Operator
on:
  workflow_dispatch:

jobs:
  create_tag_and_package_chart:
    if: ${{ github.ref != 'refs/heads/main' }}
    name: Create tag
    runs-on: ubuntu-latest
    steps:
      - name: Validate version
        run: |
          RELEASE_VERSION=$( echo ${{ github.ref }} | cut -d '/' -f 3- )
          echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV
          NUMBER='(0|[1-9][0-9]*)'
          echo ${RELEASE_VERSION} | egrep "^$NUMBER.$NUMBER(.$NUMBER)?$"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.DEVOPS_GITHUB_TOKEN }}

      - name: Create a New Tag
        run: |
          TAG_VERSION=v${RELEASE_VERSION}
          git tag ${TAG_VERSION}
          git push origin ${TAG_VERSION}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Package operator chart and add it into index.yaml
        run: |
          helm package ./helm-charts/hazelcast-platform-operator
          helm package ./helm-charts/hazelcast-platform-operator/charts/hazelcast-platform-operator-crds
          aws s3 cp s3://hazelcast-charts/index.yaml .
          helm repo index --url=https://hazelcast-charts.s3.amazonaws.com --merge ./index.yaml .

      - name: Push operator chart and index.yaml to S3 bucket
        run: |
          for CHART_TGZ in *.tgz; do aws s3 cp ${CHART_TGZ} s3://hazelcast-charts; done
          aws s3 cp ./index.yaml s3://hazelcast-charts

  slack_notify:
    name: Slack Notify
    needs: [ 'create_tag_and_package_chart' ]
    runs-on: ubuntu-latest
    if: always() && needs.create_tag_and_package_chart.result != 'success' 
    steps:
      - uses: 8398a7/action-slack@v3
        with:
          fields: repo,commit,author,action,eventName,workflow
          status: failure
          channel: "#github-actions-log"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
